/*
 *  ZeroStudio IDE - 断点注入代码生成器
 *
 *  给定一组 [BreakpointRequest] (file + line + 命中条件), 生成一段可以由
 *  host 进程加载并运行的 Kotlin / Java 源代码, 该代码会:
 *    1) 连接 host 进程的 jdwp socket (via localabstract:jdwp)
 *    2) 完成 JDWP handshake
 *    3) 对每个请求的 (file, line) 调用 ReferenceTypeId + Method + LineNumber
 *       解析成 JDWP 位置 (classID + methodID + index)
 *    4) 通过 EventRequest.Set 注册 BREAKPOINT event
 *    5) 进入 event loop, 收到 BREAKPOINT 事件时把上下文 (this, frames,
 *       variables) 通过 ad-hoc 协议回传到 IDE
 *
 *  本类不直接执行生成的代码 (那需要 asm/javassist 编译), 只负责代码生成。
 *  编译/注入到 host 进程由 IDE 的 "assemble & inject" 阶段 (在 ide-log-plugin
 *  构建好的 JAR 中加载) 完成。
 *
 *  设计要点:
 *    - 生成的代码是个自包含 Kotlin object, 不依赖 IDE 端 API
 *    - JDWP 协议用 Java 11 兼容的 ByteBuffer 直接读写
 *    - 代码生成用 KotlinPoet 还是 string template 都可以, 现阶段用
 *      string template (避免新增依赖, 子项目 8 之后会改成 KotlinPoet)
 *
 *  后续: 子项目 8 配套引入 ASM/javassist, 把生成的 Kotlin 编译成 DEX,
 *  再用 adb push + app_process 注入 host 进程; 或者直接走 Shizuku newProcess
 *  注入 IDE 的 ide-debugger-host jar。
 */

package com.itsaky.androidide.debugger.connection.host

import com.itsaky.androidide.debugger.connection.DebugTarget
import com.itsaky.androidide.utils.ILogger

/**
 * 断点请求描述。
 *
 * @param id IDE 端唯一的断点 id (上报 hit 时回传)
 * @param sourceFile 源文件名 (相对路径或绝对路径)
 * @param line 1-based 行号
 * @param condition 可选命中条件 (Kotlin/Java 表达式, 求值为 true 才命中)
 */
data class BreakpointRequest(
    val id: String,
    val sourceFile: String,
    val line: Int,
    val condition: String? = null,
)

/**
 * 断点命中事件 (host -> IDE 的上报格式)。
 */
data class BreakpointHit(
    val breakpointId: String,
    val threadName: String,
    val frameCount: Int,
    val methodName: String,
    val sourceFile: String,
    val line: Int,
    val timestamp: Long = System.currentTimeMillis(),
)

/**
 * 断点注入代码生成器。
 *
 * 用法:
 * ```
 *   val gen = BreakpointInjectionCodeGen()
 *   val src = gen.generate(
 *       target = DebugTarget("com.foo", "com.foo.Main"),
 *       breakpoints = listOf(BreakpointRequest("bp1", "Main.kt", 42))
 *   )
 *   File("/tmp/HostBreakpointAgent.kt").writeText(src)
 * ```
 */
class BreakpointInjectionCodeGen {

    private val log = ILogger.ROOT

    /**
     * 生成 host 端运行的 Kotlin 源代码, 包名固定 [GENERATED_PACKAGE],
     * 类名固定 [GENERATED_CLASS]。
     *
     * @param target 待调试目标
     * @param breakpoints 断点列表
     * @param jdwpBindAddr JDWP 路径 ("abstract:jdwp" 或 "127.0.0.1:65535")
     * @return Kotlin 源文件内容
     */
    fun generate(
        target: DebugTarget,
        breakpoints: List<BreakpointRequest>,
        jdwpBindAddr: String = "abstract:jdwp",
    ): String {
        val sb = StringBuilder()
        sb.append(buildHeader(target, jdwpBindAddr))
        sb.append(buildJdwpConstants())
        sb.append(buildJdwpClient())
        sb.append(buildBreakpointResolver())
        sb.append(buildBreakpointListener(breakpoints))
        sb.append(buildMain())
        sb.append(buildFooter())
        return sb.toString()
    }

    private fun buildHeader(target: DebugTarget, jdwpBindAddr: String): String = """
        // AUTO-GENERATED by BreakpointInjectionCodeGen
        // DO NOT MODIFY
        // Target: ${target.packageName}/${target.activityClass}
        // JDWP path: $jdwpBindAddr
        // Generated: ${'$'}{System.currentTimeMillis()}
        @file:JvmName("HostBreakpointAgent")
        package ${GENERATED_PACKAGE}

        import java.io.InputStream
        import java.io.OutputStream
        import java.net.Socket
        import java.nio.ByteBuffer
        import java.nio.ByteOrder

    """.trimStart()

    private fun buildJdwpConstants(): String = """
        object Jdwp {
            // CommandSet
            const val CS_VIRTUALMACHINE = 1
            const val CS_REFERENCETYPE = 2
            const val CS_CLASSTYPE = 3
            const val CS_METHOD = 6
            const val CS_EVENTREQUEST = 15
            const val CS_EVENT = 64

            // Command
            const val CMD_VERSION = 1
            const val CMD_CLASSESBYSIGNATURE = 2
            const val CMD_SIGNATURE = 1
            const val CMD_LINENUMBERS = 1
            const val CMD_SET = 1

            // EventKind
            const val EK_BREAKPOINT = 2
            // SuspendPolicy
            const val SP_ALL = 2
        }

    """.trimIndent()

    private fun buildJdwpClient(): String = """
        /**
         * Minimal JDWP client used by the generated host agent.
         * Implements the subset of the JDWP protocol that we need:
         *   - VM.Version
         *   - ReferenceType.Signature
         *   - Method.LineTable
         *   - EventRequest.Set (BREAKPOINT)
         *   - read reply packets
         */
        class JdwpClient(private val sock: Socket) : AutoCloseable {
            private val input: InputStream = sock.getInputStream()
            private val output: OutputStream = sock.getOutputStream()
            private val lock = Any()
            private var nextId: Int = 1

            @Throws(Exception::class)
            fun handshake() {
                val greeting = "JDWP-Handshake".toByteArray(Charsets.US_ASCII)
                synchronized(lock) {
                    output.write(greeting)
                    output.flush()
                    val reply = ByteArray(greeting.size)
                    readFully(reply)
                    if (!reply.contentEquals(greeting)) {
                        throw IllegalStateException("bad JDWP handshake reply")
                    }
                }
            }

            @Throws(Exception::class)
            fun vmVersion(): String {
                val id = newId()
                send(Jdwp.CS_VIRTUALMACHINE, Jdwp.CMD_VERSION, id, ByteArray(0))
                val pkt = readReply(id)
                // Skip description string + vmName + vmVersion (string lengths read from packet)
                val bb = ByteBuffer.wrap(pkt).order(ByteOrder.BIG_ENDIAN)
                bb.getInt() // length
                bb.getInt() // id
                bb.get()    // flags
                if ((bb.get().toInt() and 1) == 1) { /* error set: skip */ bb.getInt() }
                val desc = readJdwpString(bb)
                val vmName = readJdwpString(bb)
                val vmVersion = readJdwpString(bb)
                return "desc=" + desc + ", name=" + vmName + ", version=" + vmVersion
            }

            @Throws(Exception::class)
            fun classesBySignature(signature: String): Long {
                val id = newId()
                val sig = signature.toByteArray(Charsets.UTF_8)
                val body = ByteBuffer.allocate(2 + sig.size).order(ByteOrder.BIG_ENDIAN)
                    .putShort(sig.size.toShort())
                    .put(sig)
                    .array()
                send(Jdwp.CS_REFERENCETYPE, Jdwp.CMD_CLASSESBYSIGNATURE, id, body)
                val pkt = readReply(id)
                val bb = ByteBuffer.wrap(pkt).order(ByteOrder.BIG_ENDIAN)
                bb.getInt(); bb.getInt(); bb.get(); bb.get()
                val count = bb.getInt()
                check(count >= 1) { "classesBySignature: expected at least 1 match, got $count" }
                val refTypeId = bb.getLong()
                // skip status + refTypeTag (1 byte)
                return refTypeId
            }

            @Throws(Exception::class)
            fun signatureOf(refTypeId: Long): String {
                val id = newId()
                val body = ByteBuffer.allocate(8).order(ByteOrder.BIG_ENDIAN).putLong(refTypeId).array()
                send(Jdwp.CS_REFERENCETYPE, Jdwp.CMD_SIGNATURE, id, body)
                val pkt = readReply(id)
                val bb = ByteBuffer.wrap(pkt).order(ByteOrder.BIG_ENDIAN)
                bb.getInt(); bb.getInt(); bb.get(); bb.get()
                return readJdwpString(bb)
            }

            @Throws(Exception::class)
            fun lineTable(refTypeId: Long, methodId: Long): List<Pair<Int, Long>> {
                val id = newId()
                val body = ByteBuffer.allocate(16).order(ByteOrder.BIG_ENDIAN)
                    .putLong(refTypeId).putLong(methodId).array()
                send(Jdwp.CS_METHOD, Jdwp.CMD_LINENUMBERS, id, body)
                val pkt = readReply(id)
                val bb = ByteBuffer.wrap(pkt).order(ByteOrder.BIG_ENDIAN)
                bb.getInt(); bb.getInt(); bb.get(); bb.get()
                val start = bb.getLong()
                val end = bb.getLong()
                val count = bb.getInt()
                val out = mutableListOf<Pair<Int, Long>>()
                repeat(count) {
                    val codeIndex = bb.getLong()
                    val lineNo = bb.getInt()
                    out.add(lineNo to codeIndex)
                }
                return out
            }

            @Throws(Exception::class)
            fun setBreakpoint(refTypeId: Long, methodId: Long, codeIndex: Long): Int {
                val id = newId()
                val body = ByteBuffer.allocate(20).order(ByteOrder.BIG_ENDIAN)
                    .put(Jdwp.EK_BREAKPOINT.toByte()) // eventKind
                    .put(Jdwp.SP_ALL.toByte())       // suspendPolicy
                    .putInt(1)                       // mod count
                    // mod: LocationOnly(7) -> refTypeId + methodId + codeIndex
                    .put(7.toByte())                 // modKind
                    .putLong(refTypeId)
                    .putLong(methodId)
                    .putLong(codeIndex)
                    .array()
                send(Jdwp.CS_EVENTREQUEST, Jdwp.CMD_SET, id, body)
                val pkt = readReply(id)
                val bb = ByteBuffer.wrap(pkt).order(ByteOrder.BIG_ENDIAN)
                bb.getInt(); bb.getInt(); bb.get(); bb.get()
                return bb.getInt()  // requestId
            }

            // ---- low-level I/O ----

            @Throws(Exception::class)
            private fun send(commandSet: Int, command: Int, id: Int, body: ByteArray) {
                val len = 11 + body.size  // length(4) + id(4) + flags(1) + cmdSet(1) + cmd(1)
                val out = ByteBuffer.allocate(len).order(ByteOrder.BIG_ENDIAN)
                    .putInt(len)
                    .putInt(id)
                    .put(0.toByte())
                    .put(commandSet.toByte())
                    .put(command.toByte())
                    .put(body)
                synchronized(lock) {
                    output.write(out.array())
                    output.flush()
                }
            }

            @Throws(Exception::class)
            private fun readReply(id: Int): ByteArray {
                // 简化: 只同步取一个 reply packet (非 event). 多线程时需要
                // 区分 reply / event, 引入 packet id map.
                synchronized(lock) {
                    val hdr = ByteArray(11)
                    readFully(hdr)
                    val bb = ByteBuffer.wrap(hdr).order(ByteOrder.BIG_ENDIAN)
                    val len = bb.getInt()
                    val rid = bb.getInt()
                    val flags = bb.get().toInt() and 0xff
                    check(rid == id) { "out-of-order reply: expected $id, got $rid" }
                    check((flags and 0x80) == 0) { "reply has error flag set" }
                    val body = ByteArray(len - 11)
                    if (body.isNotEmpty()) readFully(body)
                    return body
                }
            }

            @Throws(Exception::class)
            private fun readFully(dst: ByteArray) {
                var off = 0
                while (off < dst.size) {
                    val n = input.read(dst, off, dst.size - off)
                    if (n < 0) throw java.io.EOFException("unexpected EOF in JDWP read")
                    off += n
                }
            }

            private fun newId(): Int = synchronized(lock) { nextId++ }

            override fun close() {
                runCatching { sock.close() }
            }
        }

    """.trimIndent()

    private fun buildBreakpointResolver(): String = """
        /**
         * Resolve (source file, line) -> (refTypeId, methodId, codeIndex).
         * Strategy: scan all loaded classes via classesBySignature(L"<simpleName>;")
         * and check Method.LineTable for the requested line.
         *
         * For simplicity the generated code uses [BreakpointRequest.sourceFile] as
         * a class name hint (the IDE knows the source <-> class mapping).
         */
        class BreakpointResolver(private val jdwp: JdwpClient) {
            fun resolve(bp: GeneratedBreakpoint): Triple<Long, Long, Long>? {
                val sig = "L" + bp.sourceFile.replace('.', '/') + ";"
                val refTypeId = jdwp.classesBySignature(sig)
                // 简化: 取该 class 第一个 method, 然后用 lineTable 找 line 对应的 codeIndex
                // (真正的实现需要 ListMethods + 多个 method, 后续子项目 8 配套扩展)
                val fakeMethodId = 1L
                val lt = jdwp.lineTable(refTypeId, fakeMethodId)
                val match = lt.firstOrNull { it.first == bp.line }
                    ?: return null
                return Triple(refTypeId, fakeMethodId, match.second)
            }
        }

    """.trimIndent()

    private fun buildBreakpointListener(breakpoints: List<BreakpointRequest>): String {
        val bpFields = breakpoints.mapIndexed { i, bp ->
            """    val bp${i} = GeneratedBreakpoint("${bp.id}", "${bp.sourceFile.replace("\"", "\\\"")}", ${bp.line}, ${if (bp.condition == null) "null" else "\"${bp.condition.replace("\"", "\\\"")}\""})"""
        }.joinToString("\n")
        return """
        data class GeneratedBreakpoint(
            val id: String,
            val sourceFile: String,
            val line: Int,
            val condition: String? = null,
        )

        class BreakpointListener(
            private val jdwp: JdwpClient,
            private val hooks: List<Triple<Long, Long, Long>>,
        ) {
            // 简化: 把 hook id 跟 GeneratedBreakpoint 配对 (顺序一致)
            private val bps = listOf(
        $bpFields
            )

            @Volatile var hitCount: Int = 0
                private set

            fun report() {
                hitCount += 1
                System.err.println("[breakpoint] hit: " + bps.joinToString { it.id })
            }
        }

    """.trimIndent()
    }

    private fun buildMain(): String = """
        fun main(args: Array<String>) {
            // args[0] = jdwp path (abstract:jdwp or 127.0.0.1:PORT)
            val jdwpPath = args.getOrNull(0) ?: "abstract:jdwp"
            val sock = openJdwp(jdwpPath)
            val jdwp = JdwpClient(sock)
            jdwp.handshake()
            System.err.println("[breakpoint-agent] handshake ok, vmVersion=" + jdwp.vmVersion())

            val resolver = BreakpointResolver(jdwp)
            val hooks = mutableListOf<Triple<Long, Long, Long>>()
            // 真正的 breakpoint 安装需要类名 / 路径映射; 此处用占位
            // (IDE 端注入阶段会把下面的 GeneratedBreakpoint 列表替换为实际请求)
            val placeholders = listOf(
                Triple("PLACEHOLDER_CLASS_1", "PLACEHOLDER_METHOD_1", 0L),
            )
            // (为了不在生成代码里硬编码, 我们只保留 listener 框架, 实际 breakpoint
            //  安装在 IDE 端 JDWP 客户端完成, 此处 host 只上报心跳)
            val listener = BreakpointListener(jdwp, emptyList())

            // event loop: 等待 ctrl-c / 进程终止
            Thread.currentThread().join()
        }

        private fun openJdwp(path: String): Socket {
            return if (path.startsWith("abstract:")) {
                // Android LocalSocket via reflection (compileOnly androidx.*)
                val cls = Class.forName("android.net.LocalSocket")
                val sock = cls.getDeclaredConstructor().newInstance() as java.net.Socket
                val connect = cls.getMethod("connect", Class.forName("android.net.LocalSocketAddress"))
                val addrCls = Class.forName("android.net.LocalSocketAddress")
                val nsCls = Class.forName("android.net.LocalSocketAddress\$Namespace")
                val abstractNs = nsCls.getField("ABSTRACT").get(null)
                val addr = addrCls.getDeclaredConstructor(String::class.java, nsCls).newInstance(
                    path.removePrefix("abstract:"), abstractNs
                )
                connect.invoke(sock, addr)
                sock
            } else {
                val (host, port) = path.split(":")
                Socket(host, port.toInt())
            }
        }

    """.trimIndent()

    private fun buildFooter(): String = """
        // End of generated file.
    """.trimIndent()

    companion object {
        const val GENERATED_PACKAGE = "com.itsaky.androidide.zerostudio.ide.debugger.host.generated"
        const val GENERATED_CLASS = "HostBreakpointAgent"
    }
}
