/*
 *  This file is part of android-tree-sitter.
 *
 *  android-tree-sitter library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  android-tree-sitter library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *  along with android-tree-sitter.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.itsaky.androidide.treesitter;

import com.itsaky.androidide.treesitter.annotations.GenerateNativeHeaders;
import dalvik.annotation.optimization.FastNative;

/**
 * @author Akash Yadav
 */
public class TreeSitter {

  private static int sLangVer = -1, sMinCompatLangVer = -1;

  /**
   * Loads the <code>android-tree-sitter</code> native library using
   * {@link System#loadLibrary(String)}.
   */
  public static void loadLibrary() {
    System.loadLibrary("android-tree-sitter");
  }


  /**
   * The latest ABI version that is supported by the current version of the library. When Languages
   * are generated by the Tree-sitter CLI, they are assigned an ABI version number that corresponds
   * to the current CLI version. The Tree-sitter library is generally backwards-compatible with
   * languages generated using older CLI versions, but is not forwards-compatible.
   */
  public static int getLanguageVersion() {
    if (sLangVer == -1) {
      sLangVer = Native.getLanguageVersion();
    }

    return sLangVer;
  }

  /**
   * The earliest ABI version that is supported by the current version of the library.
   */
  public static int getMinimumCompatibleLanguageVersion() {
    if (sMinCompatLangVer == -1) {
      sMinCompatLangVer = Native.getMinimumCompatibleLanguageVersion();
    }

    return sMinCompatLangVer;
  }

  // ==========================================================================
  // 关于 ts_set_allocator（不暴露 Java 绑定的设计决策）
  // ==========================================================================
  //
  // tree-sitter 0.27 的 ts_set_allocator 接受 4 个 C 函数指针用于全局替换内存分配器：
  //   void ts_set_allocator(void *(*new_malloc)(size_t),
  //                         void *(*new_calloc)(size_t, size_t),
  //                         void *(*new_realloc)(void *, size_t),
  //                         void (*new_free)(void *));
  //
  // android-tree-sitter 刻意不为此 API 提供 Java 绑定，原因如下：
  //
  // 1. Java 无法直接传递函数指针，需要 native trampoline 反向调用 Java。
  // 2. JNI 调用 Java 方法时会创建局部引用、可能触发 JVM 内部内存分配；
  //    若 Java 端 allocator 实现又依赖 tree-sitter 内存，将导致无限递归/死锁。
  // 3. ts_set_allocator 是全局的，必须在所有 tree-sitter 对象创建前调用，
  //    Android 应用无法保证此初始化时机约束。
  // 4. JVM 已统一管理内存，对 Java/Android 应用而言替换 allocator 无实际价值，
  //    反而引入性能开销和稳定性风险。
  //
  // 如有自定义内存分配需求，建议在 native 层直接调用 ts_set_allocator，
  // 不经过 JNI。

  @GenerateNativeHeaders(fileName = "meta")
  private static final class Native {

    @FastNative
    static native int getLanguageVersion();

    /**
     * The earliest ABI version that is supported by the current version of the library.
     */
    @FastNative
    static native int getMinimumCompatibleLanguageVersion();
  }
}