/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * @brief JNI 动态注册聚合头文件。
 * 负责包含所有具体语言的头文件，并提供宏来统一定义方法数组和执行注册。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

// Include generated headers for all Native classes in android-tree-sitter
#include "ts_meta.h"
#include "ts_language.h"
#include "ts_parser.h"
#include "ts_tree.h"
#include "ts_node.h"
#include "ts_tree_cursor.h"
#include "ts_lookahead_iterator.h"
#include "ts_query.h"
#include "ts_query_cursor.h"
#include "ts_utils.h"
#include "ts_wasm_store.h"


#ifndef _Included__TS_JNI_ONLOAD_
#define _Included__TS_JNI_ONLOAD_

// 自动注册宏：在 JNI_OnLoad 中调用，注册所有包含的 Native 类
#define TS_JNI_ONLOAD__AUTO_REGISTER(env) \
    TreeSitter_Native_AutoRegisterNatives(env); \
    TSLanguage_Native_AutoRegisterNatives(env); \
    TSParser_Native_AutoRegisterNatives(env); \
    TSTree_Native_AutoRegisterNatives(env); \
    TSNode_Native_AutoRegisterNatives(env); \
    TSTreeCursor_Native_AutoRegisterNatives(env); \
    TSLookaheadIterator_Native_AutoRegisterNatives(env); \
    TSQuery_Native_AutoRegisterNatives(env); \
    TSQueryCursor_Native_AutoRegisterNatives(env); \
    TSUtils_Native_AutoRegisterNatives(env); \
    TSWasmStore_Native_AutoRegisterNatives(env); \

// 定义方法数组宏：实例化 JNINativeMethod 数组
#define TS_JNI_ONLOAD__DEFINE_METHODS_ARR \
    TreeSitter_Native_DefMethodsArray; \
    TSLanguage_Native_DefMethodsArray; \
    TSParser_Native_DefMethodsArray; \
    TSTree_Native_DefMethodsArray; \
    TSNode_Native_DefMethodsArray; \
    TSTreeCursor_Native_DefMethodsArray; \
    TSLookaheadIterator_Native_DefMethodsArray; \
    TSQuery_Native_DefMethodsArray; \
    TSQueryCursor_Native_DefMethodsArray; \
    TSUtils_Native_DefMethodsArray; \
    TSWasmStore_Native_DefMethodsArray; \

#endif
