/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSLanguage.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguage__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSLanguage__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symForName
 * Signature: (J[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symForName
  (JNIEnv *env, jclass clazz, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symName
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldNameForId
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldNameForId
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldIdForName
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldIdForName
  (JNIEnv *env, jclass clazz, jlong, jbyteArray, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symType
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    langVer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_langVer
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    loadLanguage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_loadLanguage
  (JNIEnv *env, jclass clazz, jstring, jstring);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    dlclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_dlclose
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    stateCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_stateCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    nextState
 * Signature: (JSS)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_nextState
  (JNIEnv *env, jclass clazz, jlong, jshort, jshort);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_name
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    metadata
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_metadata
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    supertypes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_supertypes
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    subtypes
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_subtypes
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    isWasm
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_isWasm
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_copy
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguage__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSLanguage__Native_METHOD_SIGNATURES

// Index of method symCount of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_symCount__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symCount
 * Signature: (J)I
 */
static JNINativeMethod TSLanguage_Native_symCount= {
    .name = "symCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method fldCount of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_fldCount__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldCount
 * Signature: (J)I
 */
static JNINativeMethod TSLanguage_Native_fldCount= {
    .name = "fldCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method symForName of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_symForName__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symForName
 * Signature: (J[BIZ)I
 */
static JNINativeMethod TSLanguage_Native_symForName= {
    .name = "symForName",
    .signature = "(J[BIZ)I",
    .fnPtr = nullptr
};

// Index of method symName of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_symName__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symName
 * Signature: (JI)Ljava/lang/String;
 */
static JNINativeMethod TSLanguage_Native_symName= {
    .name = "symName",
    .signature = "(JI)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method fldNameForId of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_fldNameForId__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldNameForId
 * Signature: (JI)Ljava/lang/String;
 */
static JNINativeMethod TSLanguage_Native_fldNameForId= {
    .name = "fldNameForId",
    .signature = "(JI)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method fldIdForName of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_fldIdForName__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    fldIdForName
 * Signature: (J[BI)I
 */
static JNINativeMethod TSLanguage_Native_fldIdForName= {
    .name = "fldIdForName",
    .signature = "(J[BI)I",
    .fnPtr = nullptr
};

// Index of method symType of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_symType__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    symType
 * Signature: (JI)I
 */
static JNINativeMethod TSLanguage_Native_symType= {
    .name = "symType",
    .signature = "(JI)I",
    .fnPtr = nullptr
};

// Index of method langVer of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_langVer__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    langVer
 * Signature: (J)I
 */
static JNINativeMethod TSLanguage_Native_langVer= {
    .name = "langVer",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method loadLanguage of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_loadLanguage__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    loadLanguage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[J
 */
static JNINativeMethod TSLanguage_Native_loadLanguage= {
    .name = "loadLanguage",
    .signature = "(Ljava/lang/String;Ljava/lang/String;)[J",
    .fnPtr = nullptr
};

// Index of method dlclose of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_dlclose__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    dlclose
 * Signature: (J)V
 */
static JNINativeMethod TSLanguage_Native_dlclose= {
    .name = "dlclose",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method stateCount of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_stateCount__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    stateCount
 * Signature: (J)I
 */
static JNINativeMethod TSLanguage_Native_stateCount= {
    .name = "stateCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method nextState of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_nextState__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    nextState
 * Signature: (JSS)S
 */
static JNINativeMethod TSLanguage_Native_nextState= {
    .name = "nextState",
    .signature = "(JSS)S",
    .fnPtr = nullptr
};

// Index of method name of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_name__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    name
 * Signature: (J)Ljava/lang/String;
 */
static JNINativeMethod TSLanguage_Native_name= {
    .name = "name",
    .signature = "(J)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method metadata of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_metadata__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    metadata
 * Signature: (J)[I
 */
static JNINativeMethod TSLanguage_Native_metadata= {
    .name = "metadata",
    .signature = "(J)[I",
    .fnPtr = nullptr
};

// Index of method supertypes of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_supertypes__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    supertypes
 * Signature: (J)[I
 */
static JNINativeMethod TSLanguage_Native_supertypes= {
    .name = "supertypes",
    .signature = "(J)[I",
    .fnPtr = nullptr
};

// Index of method subtypes of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_subtypes__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    subtypes
 * Signature: (JI)[I
 */
static JNINativeMethod TSLanguage_Native_subtypes= {
    .name = "subtypes",
    .signature = "(JI)[I",
    .fnPtr = nullptr
};

// Index of method isWasm of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_isWasm__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    isWasm
 * Signature: (J)Z
 */
static JNINativeMethod TSLanguage_Native_isWasm= {
    .name = "isWasm",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method copy of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_copy__ARR_IDX 17

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    copy
 * Signature: (J)J
 */
static JNINativeMethod TSLanguage_Native_copy= {
    .name = "copy",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSLanguage.Native in _TSLanguage_Native_METHODS array
#define TSLanguage_Native_delete__ARR_IDX 18

/*
 * Class:     com.itsaky.androidide.treesitter.TSLanguage.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSLanguage_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSLanguage$Native
void TSLanguage_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSLanguage_Native_METHODS
#define _TSLanguage_Native_METHOD_COUNT 19
// All native methods in class com/itsaky/androidide/treesitter/TSLanguage$Native
#define TSLanguage_Native_DefMethodsArray \
    JNINativeMethod _TSLanguage_Native_METHODS[] = { \
        TSLanguage_Native_symCount, \
        TSLanguage_Native_fldCount, \
        TSLanguage_Native_symForName, \
        TSLanguage_Native_symName, \
        TSLanguage_Native_fldNameForId, \
        TSLanguage_Native_fldIdForName, \
        TSLanguage_Native_symType, \
        TSLanguage_Native_langVer, \
        TSLanguage_Native_loadLanguage, \
        TSLanguage_Native_dlclose, \
        TSLanguage_Native_stateCount, \
        TSLanguage_Native_nextState, \
        TSLanguage_Native_name, \
        TSLanguage_Native_metadata, \
        TSLanguage_Native_supertypes, \
        TSLanguage_Native_subtypes, \
        TSLanguage_Native_isWasm, \
        TSLanguage_Native_copy, \
        TSLanguage_Native_delete, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSLanguage$Native with the given JNIEnv
#define TSLanguage_Native_AutoRegisterNatives(_env) \
    int _TSLanguage_Native_rc; \
    TSLanguage_Native__SetJniMethods(&_TSLanguage_Native_METHODS[0], _TSLanguage_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSLanguage_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSLanguage_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSLanguage_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSLanguage$Native"); \
    if (_TSLanguage_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSLanguage$Native"); \
        return JNI_ERR; \
    } \
    _TSLanguage_Native_rc = _env->RegisterNatives(_TSLanguage_Native_class, _TSLanguage_Native_METHODS, _TSLanguage_Native_METHOD_COUNT); \
    if (_TSLanguage_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSLanguage$Native'. Result: %d", _TSLanguage_Native_rc); \
        return _TSLanguage_Native_rc; \
    }\


#endif
#endif
