/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSLookaheadIterator.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSLookaheadIterator__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSLookaheadIterator__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    newIterator
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_newIterator
  (JNIEnv *env, jclass clazz, jlong, jshort);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    next
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_next
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    currentSymbol
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_currentSymbol
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    currentSymbolName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_currentSymbolName
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    resetState
 * Signature: (JS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_resetState
  (JNIEnv *env, jclass clazz, jlong, jshort);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    reset
 * Signature: (JJS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_reset
  (JNIEnv *env, jclass clazz, jlong, jlong, jshort);

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    language
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLookaheadIterator_00024Native_language
  (JNIEnv *env, jclass clazz, jlong);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSLookaheadIterator__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSLookaheadIterator__Native_METHOD_SIGNATURES

// Index of method newIterator of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_newIterator__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    newIterator
 * Signature: (JS)J
 */
static JNINativeMethod TSLookaheadIterator_Native_newIterator= {
    .name = "newIterator",
    .signature = "(JS)J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSLookaheadIterator_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method next of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_next__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    next
 * Signature: (J)Z
 */
static JNINativeMethod TSLookaheadIterator_Native_next= {
    .name = "next",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method currentSymbol of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_currentSymbol__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    currentSymbol
 * Signature: (J)S
 */
static JNINativeMethod TSLookaheadIterator_Native_currentSymbol= {
    .name = "currentSymbol",
    .signature = "(J)S",
    .fnPtr = nullptr
};

// Index of method currentSymbolName of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_currentSymbolName__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    currentSymbolName
 * Signature: (J)Ljava/lang/String;
 */
static JNINativeMethod TSLookaheadIterator_Native_currentSymbolName= {
    .name = "currentSymbolName",
    .signature = "(J)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method resetState of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_resetState__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    resetState
 * Signature: (JS)Z
 */
static JNINativeMethod TSLookaheadIterator_Native_resetState= {
    .name = "resetState",
    .signature = "(JS)Z",
    .fnPtr = nullptr
};

// Index of method reset of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_reset__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    reset
 * Signature: (JJS)Z
 */
static JNINativeMethod TSLookaheadIterator_Native_reset= {
    .name = "reset",
    .signature = "(JJS)Z",
    .fnPtr = nullptr
};

// Index of method language of class com.itsaky.androidide.treesitter.TSLookaheadIterator.Native in _TSLookaheadIterator_Native_METHODS array
#define TSLookaheadIterator_Native_language__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSLookaheadIterator.Native
 * Method:    language
 * Signature: (J)J
 */
static JNINativeMethod TSLookaheadIterator_Native_language= {
    .name = "language",
    .signature = "(J)J",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSLookaheadIterator$Native
void TSLookaheadIterator_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSLookaheadIterator_Native_METHODS
#define _TSLookaheadIterator_Native_METHOD_COUNT 8
// All native methods in class com/itsaky/androidide/treesitter/TSLookaheadIterator$Native
#define TSLookaheadIterator_Native_DefMethodsArray \
    JNINativeMethod _TSLookaheadIterator_Native_METHODS[] = { \
        TSLookaheadIterator_Native_newIterator, \
        TSLookaheadIterator_Native_delete, \
        TSLookaheadIterator_Native_next, \
        TSLookaheadIterator_Native_currentSymbol, \
        TSLookaheadIterator_Native_currentSymbolName, \
        TSLookaheadIterator_Native_resetState, \
        TSLookaheadIterator_Native_reset, \
        TSLookaheadIterator_Native_language, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSLookaheadIterator$Native with the given JNIEnv
#define TSLookaheadIterator_Native_AutoRegisterNatives(_env) \
    int _TSLookaheadIterator_Native_rc; \
    TSLookaheadIterator_Native__SetJniMethods(&_TSLookaheadIterator_Native_METHODS[0], _TSLookaheadIterator_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSLookaheadIterator_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSLookaheadIterator_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSLookaheadIterator_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSLookaheadIterator$Native"); \
    if (_TSLookaheadIterator_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSLookaheadIterator$Native"); \
        return JNI_ERR; \
    } \
    _TSLookaheadIterator_Native_rc = _env->RegisterNatives(_TSLookaheadIterator_Native_class, _TSLookaheadIterator_Native_METHODS, _TSLookaheadIterator_Native_METHOD_COUNT); \
    if (_TSLookaheadIterator_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSLookaheadIterator$Native'. Result: %d", _TSLookaheadIterator_Native_rc); \
        return _TSLookaheadIterator_Native_rc; \
    }\


#endif
#endif
