/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TreeSitter.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TreeSitter__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TreeSitter__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TreeSitter.Native
 * Method:    getLanguageVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TreeSitter_00024Native_getLanguageVersion
  (JNIEnv *env, jclass clazz);

/*
 * Class:     com.itsaky.androidide.treesitter.TreeSitter.Native
 * Method:    getMinimumCompatibleLanguageVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TreeSitter_00024Native_getMinimumCompatibleLanguageVersion
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TreeSitter__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TreeSitter__Native_METHOD_SIGNATURES

// Index of method getLanguageVersion of class com.itsaky.androidide.treesitter.TreeSitter.Native in _TreeSitter_Native_METHODS array
#define TreeSitter_Native_getLanguageVersion__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TreeSitter.Native
 * Method:    getLanguageVersion
 * Signature: ()I
 */
static JNINativeMethod TreeSitter_Native_getLanguageVersion= {
    .name = "getLanguageVersion",
    .signature = "()I",
    .fnPtr = nullptr
};

// Index of method getMinimumCompatibleLanguageVersion of class com.itsaky.androidide.treesitter.TreeSitter.Native in _TreeSitter_Native_METHODS array
#define TreeSitter_Native_getMinimumCompatibleLanguageVersion__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TreeSitter.Native
 * Method:    getMinimumCompatibleLanguageVersion
 * Signature: ()I
 */
static JNINativeMethod TreeSitter_Native_getMinimumCompatibleLanguageVersion= {
    .name = "getMinimumCompatibleLanguageVersion",
    .signature = "()I",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TreeSitter$Native
void TreeSitter_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TreeSitter_Native_METHODS
#define _TreeSitter_Native_METHOD_COUNT 2
// All native methods in class com/itsaky/androidide/treesitter/TreeSitter$Native
#define TreeSitter_Native_DefMethodsArray \
    JNINativeMethod _TreeSitter_Native_METHODS[] = { \
        TreeSitter_Native_getLanguageVersion, \
        TreeSitter_Native_getMinimumCompatibleLanguageVersion, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TreeSitter$Native with the given JNIEnv
#define TreeSitter_Native_AutoRegisterNatives(_env) \
    int _TreeSitter_Native_rc; \
    TreeSitter_Native__SetJniMethods(&_TreeSitter_Native_METHODS[0], _TreeSitter_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TreeSitter_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TreeSitter_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TreeSitter_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TreeSitter$Native"); \
    if (_TreeSitter_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TreeSitter$Native"); \
        return JNI_ERR; \
    } \
    _TreeSitter_Native_rc = _env->RegisterNatives(_TreeSitter_Native_class, _TreeSitter_Native_METHODS, _TreeSitter_Native_METHOD_COUNT); \
    if (_TreeSitter_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TreeSitter$Native'. Result: %d", _TreeSitter_Native_rc); \
        return _TreeSitter_Native_rc; \
    }\


#endif
#endif
