/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSNode.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSNode__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSNode__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    canAccess
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_canAccess
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getParent
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getParent
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    childWithDescendant
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_childWithDescendant
  (JNIEnv *env, jclass clazz, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildAt
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getChildAt
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedChildAt
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNamedChildAt
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildByFieldName
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;[BI)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getChildByFieldName
  (JNIEnv *env, jclass clazz, jobject, jbyteArray, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFieldNameForChild
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getFieldNameForChild
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    fieldNameForNamedChild
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_fieldNameForNamedChild
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildByFieldId
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getChildByFieldId
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNextSibling
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getPreviousSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getPreviousSibling
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextNamedSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNextNamedSibling
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getPreviousNamedSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getPreviousNamedSibling
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFirstChildForByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getFirstChildForByte
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFirstNamedChildForByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getFirstNamedChildForByte
  (JNIEnv *env, jclass clazz, jobject, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantForByteRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getDescendantForByteRange
  (JNIEnv *env, jclass clazz, jobject, jint, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantForPointRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getDescendantForPointRange
  (JNIEnv *env, jclass clazz, jobject, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedDescendantForByteRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNamedDescendantForByteRange
  (JNIEnv *env, jclass clazz, jobject, jint, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedDescendantForPointRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNamedDescendantForPointRange
  (JNIEnv *env, jclass clazz, jobject, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isEqualTo
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isEqualTo
  (JNIEnv *env, jclass clazz, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getChildCount
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedChildCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNamedChildCount
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNodeString
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNodeString
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getStartByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getStartByte
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getEndByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getEndByte
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getStartPoint
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getStartPoint
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getEndPoint
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getEndPoint
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getType
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getType
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getSymbol
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getSymbol
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getGrammarSymbol
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getGrammarSymbol
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isNull
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isNull
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isNamed
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isNamed
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isExtra
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isExtra
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isMissing
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isMissing
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    hasChanges
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_hasChanges
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    hasErrors
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_hasErrors
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isError
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_isError
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getParseState
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getParseState
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    edit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_edit
  (JNIEnv *env, jclass clazz, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextParseState
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getNextParseState
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getDescendantCount
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getGrammarType
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getGrammarType
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getLanguage
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSNode_00024Native_getLanguage
  (JNIEnv *env, jclass clazz, jobject);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSNode__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSNode__Native_METHOD_SIGNATURES

// Index of method canAccess of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_canAccess__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    canAccess
 * Signature: (J)Z
 */
static JNINativeMethod TSNode_Native_canAccess= {
    .name = "canAccess",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method getParent of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getParent__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getParent
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getParent= {
    .name = "getParent",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method childWithDescendant of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_childWithDescendant__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    childWithDescendant
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_childWithDescendant= {
    .name = "childWithDescendant",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getChildAt of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getChildAt__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildAt
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getChildAt= {
    .name = "getChildAt",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getNamedChildAt of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNamedChildAt__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedChildAt
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getNamedChildAt= {
    .name = "getNamedChildAt",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getChildByFieldName of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getChildByFieldName__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildByFieldName
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;[BI)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getChildByFieldName= {
    .name = "getChildByFieldName",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;[BI)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getFieldNameForChild of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getFieldNameForChild__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFieldNameForChild
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;
 */
static JNINativeMethod TSNode_Native_getFieldNameForChild= {
    .name = "getFieldNameForChild",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method fieldNameForNamedChild of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_fieldNameForNamedChild__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    fieldNameForNamedChild
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;
 */
static JNINativeMethod TSNode_Native_fieldNameForNamedChild= {
    .name = "fieldNameForNamedChild",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method getChildByFieldId of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getChildByFieldId__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildByFieldId
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getChildByFieldId= {
    .name = "getChildByFieldId",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getNextSibling of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNextSibling__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getNextSibling= {
    .name = "getNextSibling",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getPreviousSibling of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getPreviousSibling__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getPreviousSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getPreviousSibling= {
    .name = "getPreviousSibling",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getNextNamedSibling of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNextNamedSibling__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextNamedSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getNextNamedSibling= {
    .name = "getNextNamedSibling",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getPreviousNamedSibling of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getPreviousNamedSibling__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getPreviousNamedSibling
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getPreviousNamedSibling= {
    .name = "getPreviousNamedSibling",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getFirstChildForByte of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getFirstChildForByte__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFirstChildForByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getFirstChildForByte= {
    .name = "getFirstChildForByte",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getFirstNamedChildForByte of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getFirstNamedChildForByte__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getFirstNamedChildForByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getFirstNamedChildForByte= {
    .name = "getFirstNamedChildForByte",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;I)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getDescendantForByteRange of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getDescendantForByteRange__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantForByteRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getDescendantForByteRange= {
    .name = "getDescendantForByteRange",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getDescendantForPointRange of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getDescendantForPointRange__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantForPointRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getDescendantForPointRange= {
    .name = "getDescendantForPointRange",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getNamedDescendantForByteRange of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNamedDescendantForByteRange__ARR_IDX 17

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedDescendantForByteRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getNamedDescendantForByteRange= {
    .name = "getNamedDescendantForByteRange",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;II)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method getNamedDescendantForPointRange of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNamedDescendantForPointRange__ARR_IDX 18

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedDescendantForPointRange
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSNode_Native_getNamedDescendantForPointRange= {
    .name = "getNamedDescendantForPointRange",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method isEqualTo of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isEqualTo__ARR_IDX 19

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isEqualTo
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isEqualTo= {
    .name = "isEqualTo",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method getChildCount of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getChildCount__ARR_IDX 20

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getChildCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
static JNINativeMethod TSNode_Native_getChildCount= {
    .name = "getChildCount",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)I",
    .fnPtr = nullptr
};

// Index of method getNamedChildCount of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNamedChildCount__ARR_IDX 21

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNamedChildCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
static JNINativeMethod TSNode_Native_getNamedChildCount= {
    .name = "getNamedChildCount",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)I",
    .fnPtr = nullptr
};

// Index of method getNodeString of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNodeString__ARR_IDX 22

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNodeString
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
static JNINativeMethod TSNode_Native_getNodeString= {
    .name = "getNodeString",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method getStartByte of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getStartByte__ARR_IDX 23

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getStartByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
static JNINativeMethod TSNode_Native_getStartByte= {
    .name = "getStartByte",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)I",
    .fnPtr = nullptr
};

// Index of method getEndByte of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getEndByte__ARR_IDX 24

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getEndByte
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
static JNINativeMethod TSNode_Native_getEndByte= {
    .name = "getEndByte",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)I",
    .fnPtr = nullptr
};

// Index of method getStartPoint of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getStartPoint__ARR_IDX 25

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getStartPoint
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;
 */
static JNINativeMethod TSNode_Native_getStartPoint= {
    .name = "getStartPoint",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;",
    .fnPtr = nullptr
};

// Index of method getEndPoint of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getEndPoint__ARR_IDX 26

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getEndPoint
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;
 */
static JNINativeMethod TSNode_Native_getEndPoint= {
    .name = "getEndPoint",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Lcom/itsaky/androidide/treesitter/TSPoint;",
    .fnPtr = nullptr
};

// Index of method getType of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getType__ARR_IDX 27

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getType
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
static JNINativeMethod TSNode_Native_getType= {
    .name = "getType",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method getSymbol of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getSymbol__ARR_IDX 28

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getSymbol
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
static JNINativeMethod TSNode_Native_getSymbol= {
    .name = "getSymbol",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)S",
    .fnPtr = nullptr
};

// Index of method getGrammarSymbol of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getGrammarSymbol__ARR_IDX 29

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getGrammarSymbol
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
static JNINativeMethod TSNode_Native_getGrammarSymbol= {
    .name = "getGrammarSymbol",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)S",
    .fnPtr = nullptr
};

// Index of method isNull of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isNull__ARR_IDX 30

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isNull
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isNull= {
    .name = "isNull",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method isNamed of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isNamed__ARR_IDX 31

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isNamed
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isNamed= {
    .name = "isNamed",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method isExtra of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isExtra__ARR_IDX 32

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isExtra
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isExtra= {
    .name = "isExtra",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method isMissing of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isMissing__ARR_IDX 33

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isMissing
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isMissing= {
    .name = "isMissing",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method hasChanges of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_hasChanges__ARR_IDX 34

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    hasChanges
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_hasChanges= {
    .name = "hasChanges",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method hasErrors of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_hasErrors__ARR_IDX 35

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    hasErrors
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_hasErrors= {
    .name = "hasErrors",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method isError of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_isError__ARR_IDX 36

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    isError
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Z
 */
static JNINativeMethod TSNode_Native_isError= {
    .name = "isError",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Z",
    .fnPtr = nullptr
};

// Index of method getParseState of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getParseState__ARR_IDX 37

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getParseState
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
static JNINativeMethod TSNode_Native_getParseState= {
    .name = "getParseState",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)S",
    .fnPtr = nullptr
};

// Index of method edit of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_edit__ARR_IDX 38

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    edit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
static JNINativeMethod TSNode_Native_edit= {
    .name = "edit",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V",
    .fnPtr = nullptr
};

// Index of method getNextParseState of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getNextParseState__ARR_IDX 39

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getNextParseState
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)S
 */
static JNINativeMethod TSNode_Native_getNextParseState= {
    .name = "getNextParseState",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)S",
    .fnPtr = nullptr
};

// Index of method getDescendantCount of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getDescendantCount__ARR_IDX 40

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getDescendantCount
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)I
 */
static JNINativeMethod TSNode_Native_getDescendantCount= {
    .name = "getDescendantCount",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)I",
    .fnPtr = nullptr
};

// Index of method getGrammarType of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getGrammarType__ARR_IDX 41

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getGrammarType
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;
 */
static JNINativeMethod TSNode_Native_getGrammarType= {
    .name = "getGrammarType",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method getLanguage of class com.itsaky.androidide.treesitter.TSNode.Native in _TSNode_Native_METHODS array
#define TSNode_Native_getLanguage__ARR_IDX 42

/*
 * Class:     com.itsaky.androidide.treesitter.TSNode.Native
 * Method:    getLanguage
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)J
 */
static JNINativeMethod TSNode_Native_getLanguage= {
    .name = "getLanguage",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)J",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSNode$Native
void TSNode_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSNode_Native_METHODS
#define _TSNode_Native_METHOD_COUNT 43
// All native methods in class com/itsaky/androidide/treesitter/TSNode$Native
#define TSNode_Native_DefMethodsArray \
    JNINativeMethod _TSNode_Native_METHODS[] = { \
        TSNode_Native_canAccess, \
        TSNode_Native_getParent, \
        TSNode_Native_childWithDescendant, \
        TSNode_Native_getChildAt, \
        TSNode_Native_getNamedChildAt, \
        TSNode_Native_getChildByFieldName, \
        TSNode_Native_getFieldNameForChild, \
        TSNode_Native_fieldNameForNamedChild, \
        TSNode_Native_getChildByFieldId, \
        TSNode_Native_getNextSibling, \
        TSNode_Native_getPreviousSibling, \
        TSNode_Native_getNextNamedSibling, \
        TSNode_Native_getPreviousNamedSibling, \
        TSNode_Native_getFirstChildForByte, \
        TSNode_Native_getFirstNamedChildForByte, \
        TSNode_Native_getDescendantForByteRange, \
        TSNode_Native_getDescendantForPointRange, \
        TSNode_Native_getNamedDescendantForByteRange, \
        TSNode_Native_getNamedDescendantForPointRange, \
        TSNode_Native_isEqualTo, \
        TSNode_Native_getChildCount, \
        TSNode_Native_getNamedChildCount, \
        TSNode_Native_getNodeString, \
        TSNode_Native_getStartByte, \
        TSNode_Native_getEndByte, \
        TSNode_Native_getStartPoint, \
        TSNode_Native_getEndPoint, \
        TSNode_Native_getType, \
        TSNode_Native_getSymbol, \
        TSNode_Native_getGrammarSymbol, \
        TSNode_Native_isNull, \
        TSNode_Native_isNamed, \
        TSNode_Native_isExtra, \
        TSNode_Native_isMissing, \
        TSNode_Native_hasChanges, \
        TSNode_Native_hasErrors, \
        TSNode_Native_isError, \
        TSNode_Native_getParseState, \
        TSNode_Native_edit, \
        TSNode_Native_getNextParseState, \
        TSNode_Native_getDescendantCount, \
        TSNode_Native_getGrammarType, \
        TSNode_Native_getLanguage, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSNode$Native with the given JNIEnv
#define TSNode_Native_AutoRegisterNatives(_env) \
    int _TSNode_Native_rc; \
    TSNode_Native__SetJniMethods(&_TSNode_Native_METHODS[0], _TSNode_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSNode_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSNode_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSNode_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSNode$Native"); \
    if (_TSNode_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSNode$Native"); \
        return JNI_ERR; \
    } \
    _TSNode_Native_rc = _env->RegisterNatives(_TSNode_Native_class, _TSNode_Native_METHODS, _TSNode_Native_METHOD_COUNT); \
    if (_TSNode_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSNode$Native'. Result: %d", _TSNode_Native_rc); \
        return _TSNode_Native_rc; \
    }\


#endif
#endif
