/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSParser.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSParser__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSParser__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    newParser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_newParser
  (JNIEnv *env, jclass clazz);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setLanguage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setLanguage
  (JNIEnv *env, jclass clazz, jlong, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getLanguage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_getLanguage
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_reset
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setTimeout
  (JNIEnv *env, jclass clazz, jlong, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getTimeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_getTimeout
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setIncludedRanges
 * Signature: (J[Lcom/itsaky/androidide/treesitter/TSRange;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setIncludedRanges
  (JNIEnv *env, jclass clazz, jlong, jobjectArray);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getIncludedRanges
 * Signature: (J)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
JNIEXPORT jobjectArray JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_getIncludedRanges
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    parse
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_parse
  (JNIEnv *env, jclass clazz, jlong, jlong, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    parseUtf8Bytes
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_parseUtf8Bytes
  (JNIEnv *env, jclass clazz, jlong, jlong, jbyteArray);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    requestCancellation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_requestCancellation
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setWasmStore
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setWasmStore
  (JNIEnv *env, jclass clazz, jlong, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    takeWasmStore
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_takeWasmStore
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    printDotGraphs
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_printDotGraphs
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setLogger
 * Signature: (JLcom/itsaky/androidide/treesitter/TSLogger;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setLogger
  (JNIEnv *env, jclass clazz, jlong, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getLogger
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSLogger;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_getLogger
  (JNIEnv *env, jclass clazz, jlong);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSParser__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSParser__Native_METHOD_SIGNATURES

// Index of method newParser of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_newParser__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    newParser
 * Signature: ()J
 */
static JNINativeMethod TSParser_Native_newParser= {
    .name = "newParser",
    .signature = "()J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSParser_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method setLanguage of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_setLanguage__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setLanguage
 * Signature: (JJ)Z
 */
static JNINativeMethod TSParser_Native_setLanguage= {
    .name = "setLanguage",
    .signature = "(JJ)Z",
    .fnPtr = nullptr
};

// Index of method getLanguage of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_getLanguage__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getLanguage
 * Signature: (J)J
 */
static JNINativeMethod TSParser_Native_getLanguage= {
    .name = "getLanguage",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method reset of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_reset__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    reset
 * Signature: (J)V
 */
static JNINativeMethod TSParser_Native_reset= {
    .name = "reset",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method setTimeout of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_setTimeout__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setTimeout
 * Signature: (JJ)V
 */
static JNINativeMethod TSParser_Native_setTimeout= {
    .name = "setTimeout",
    .signature = "(JJ)V",
    .fnPtr = nullptr
};

// Index of method getTimeout of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_getTimeout__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getTimeout
 * Signature: (J)J
 */
static JNINativeMethod TSParser_Native_getTimeout= {
    .name = "getTimeout",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method setIncludedRanges of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_setIncludedRanges__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setIncludedRanges
 * Signature: (J[Lcom/itsaky/androidide/treesitter/TSRange;)Z
 */
static JNINativeMethod TSParser_Native_setIncludedRanges= {
    .name = "setIncludedRanges",
    .signature = "(J[Lcom/itsaky/androidide/treesitter/TSRange;)Z",
    .fnPtr = nullptr
};

// Index of method getIncludedRanges of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_getIncludedRanges__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getIncludedRanges
 * Signature: (J)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
static JNINativeMethod TSParser_Native_getIncludedRanges= {
    .name = "getIncludedRanges",
    .signature = "(J)[Lcom/itsaky/androidide/treesitter/TSRange;",
    .fnPtr = nullptr
};

// Index of method parse of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_parse__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    parse
 * Signature: (JJJ)J
 */
static JNINativeMethod TSParser_Native_parse= {
    .name = "parse",
    .signature = "(JJJ)J",
    .fnPtr = nullptr
};

// Index of method parseUtf8Bytes of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_parseUtf8Bytes__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    parseUtf8Bytes
 * Signature: (JJ[B)J
 */
static JNINativeMethod TSParser_Native_parseUtf8Bytes= {
    .name = "parseUtf8Bytes",
    .signature = "(JJ[B)J",
    .fnPtr = nullptr
};

// Index of method requestCancellation of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_requestCancellation__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    requestCancellation
 * Signature: (J)Z
 */
static JNINativeMethod TSParser_Native_requestCancellation= {
    .name = "requestCancellation",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method setWasmStore of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_setWasmStore__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setWasmStore
 * Signature: (JJ)V
 */
static JNINativeMethod TSParser_Native_setWasmStore= {
    .name = "setWasmStore",
    .signature = "(JJ)V",
    .fnPtr = nullptr
};

// Index of method takeWasmStore of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_takeWasmStore__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    takeWasmStore
 * Signature: (J)J
 */
static JNINativeMethod TSParser_Native_takeWasmStore= {
    .name = "takeWasmStore",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method printDotGraphs of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_printDotGraphs__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    printDotGraphs
 * Signature: (JI)V
 */
static JNINativeMethod TSParser_Native_printDotGraphs= {
    .name = "printDotGraphs",
    .signature = "(JI)V",
    .fnPtr = nullptr
};

// Index of method setLogger of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_setLogger__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    setLogger
 * Signature: (JLcom/itsaky/androidide/treesitter/TSLogger;)V
 */
static JNINativeMethod TSParser_Native_setLogger= {
    .name = "setLogger",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSLogger;)V",
    .fnPtr = nullptr
};

// Index of method getLogger of class com.itsaky.androidide.treesitter.TSParser.Native in _TSParser_Native_METHODS array
#define TSParser_Native_getLogger__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.TSParser.Native
 * Method:    getLogger
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSLogger;
 */
static JNINativeMethod TSParser_Native_getLogger= {
    .name = "getLogger",
    .signature = "(J)Lcom/itsaky/androidide/treesitter/TSLogger;",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSParser$Native
void TSParser_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSParser_Native_METHODS
#define _TSParser_Native_METHOD_COUNT 17
// All native methods in class com/itsaky/androidide/treesitter/TSParser$Native
#define TSParser_Native_DefMethodsArray \
    JNINativeMethod _TSParser_Native_METHODS[] = { \
        TSParser_Native_newParser, \
        TSParser_Native_delete, \
        TSParser_Native_setLanguage, \
        TSParser_Native_getLanguage, \
        TSParser_Native_reset, \
        TSParser_Native_setTimeout, \
        TSParser_Native_getTimeout, \
        TSParser_Native_setIncludedRanges, \
        TSParser_Native_getIncludedRanges, \
        TSParser_Native_parse, \
        TSParser_Native_parseUtf8Bytes, \
        TSParser_Native_requestCancellation, \
        TSParser_Native_setWasmStore, \
        TSParser_Native_takeWasmStore, \
        TSParser_Native_printDotGraphs, \
        TSParser_Native_setLogger, \
        TSParser_Native_getLogger, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSParser$Native with the given JNIEnv
#define TSParser_Native_AutoRegisterNatives(_env) \
    int _TSParser_Native_rc; \
    TSParser_Native__SetJniMethods(&_TSParser_Native_METHODS[0], _TSParser_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSParser_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSParser_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSParser_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSParser$Native"); \
    if (_TSParser_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSParser$Native"); \
        return JNI_ERR; \
    } \
    _TSParser_Native_rc = _env->RegisterNatives(_TSParser_Native_class, _TSParser_Native_METHODS, _TSParser_Native_METHOD_COUNT); \
    if (_TSParser_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSParser$Native'. Result: %d", _TSParser_Native_rc); \
        return _TSParser_Native_rc; \
    }\


#endif
#endif
