/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSQueryCursor.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSQueryCursor__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSQueryCursor__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    newCursor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_newCursor
  (JNIEnv *env, jclass clazz);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    exec
 * Signature: (JJLcom/itsaky/androidide/treesitter/TSNode;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_exec
  (JNIEnv *env, jclass clazz, jlong, jlong, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    execWithOptions
 * Signature: (JJLcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSQueryProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_execWithOptions
  (JNIEnv *env, jclass clazz, jlong, jlong, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    releaseProgressCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_releaseProgressCallback
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    exceededMatchLimit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_exceededMatchLimit
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setMatchLimit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setMatchLimit
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    getMatchLimit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_getMatchLimit
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setByteRange
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setByteRange
  (JNIEnv *env, jclass clazz, jlong, jint, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setPointRange
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setPointRange
  (JNIEnv *env, jclass clazz, jlong, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    nextMatch
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSQueryMatch;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_nextMatch
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    nextCapture
 * Signature: (J[I)Lcom/itsaky/androidide/treesitter/TSQueryMatch;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_nextCapture
  (JNIEnv *env, jclass clazz, jlong, jintArray);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setContainingByteRange
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setContainingByteRange
  (JNIEnv *env, jclass clazz, jlong, jint, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setContainingPointRange
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setContainingPointRange
  (JNIEnv *env, jclass clazz, jlong, jobject, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setMaxStartDepth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_setMaxStartDepth
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    removeMatch
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_removeMatch
  (JNIEnv *env, jclass clazz, jlong, jint);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSQueryCursor__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSQueryCursor__Native_METHOD_SIGNATURES

// Index of method newCursor of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_newCursor__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    newCursor
 * Signature: ()J
 */
static JNINativeMethod TSQueryCursor_Native_newCursor= {
    .name = "newCursor",
    .signature = "()J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSQueryCursor_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method exec of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_exec__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    exec
 * Signature: (JJLcom/itsaky/androidide/treesitter/TSNode;)V
 */
static JNINativeMethod TSQueryCursor_Native_exec= {
    .name = "exec",
    .signature = "(JJLcom/itsaky/androidide/treesitter/TSNode;)V",
    .fnPtr = nullptr
};

// Index of method execWithOptions of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_execWithOptions__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    execWithOptions
 * Signature: (JJLcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSQueryProgressCallback;)V
 */
static JNINativeMethod TSQueryCursor_Native_execWithOptions= {
    .name = "execWithOptions",
    .signature = "(JJLcom/itsaky/androidide/treesitter/TSNode;Lcom/itsaky/androidide/treesitter/TSQueryProgressCallback;)V",
    .fnPtr = nullptr
};

// Index of method releaseProgressCallback of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_releaseProgressCallback__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    releaseProgressCallback
 * Signature: (J)V
 */
static JNINativeMethod TSQueryCursor_Native_releaseProgressCallback= {
    .name = "releaseProgressCallback",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method exceededMatchLimit of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_exceededMatchLimit__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    exceededMatchLimit
 * Signature: (J)Z
 */
static JNINativeMethod TSQueryCursor_Native_exceededMatchLimit= {
    .name = "exceededMatchLimit",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method setMatchLimit of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setMatchLimit__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setMatchLimit
 * Signature: (JI)V
 */
static JNINativeMethod TSQueryCursor_Native_setMatchLimit= {
    .name = "setMatchLimit",
    .signature = "(JI)V",
    .fnPtr = nullptr
};

// Index of method getMatchLimit of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_getMatchLimit__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    getMatchLimit
 * Signature: (J)I
 */
static JNINativeMethod TSQueryCursor_Native_getMatchLimit= {
    .name = "getMatchLimit",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method setByteRange of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setByteRange__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setByteRange
 * Signature: (JII)Z
 */
static JNINativeMethod TSQueryCursor_Native_setByteRange= {
    .name = "setByteRange",
    .signature = "(JII)Z",
    .fnPtr = nullptr
};

// Index of method setPointRange of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setPointRange__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setPointRange
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z
 */
static JNINativeMethod TSQueryCursor_Native_setPointRange= {
    .name = "setPointRange",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z",
    .fnPtr = nullptr
};

// Index of method nextMatch of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_nextMatch__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    nextMatch
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSQueryMatch;
 */
static JNINativeMethod TSQueryCursor_Native_nextMatch= {
    .name = "nextMatch",
    .signature = "(J)Lcom/itsaky/androidide/treesitter/TSQueryMatch;",
    .fnPtr = nullptr
};

// Index of method nextCapture of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_nextCapture__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    nextCapture
 * Signature: (J[I)Lcom/itsaky/androidide/treesitter/TSQueryMatch;
 */
static JNINativeMethod TSQueryCursor_Native_nextCapture= {
    .name = "nextCapture",
    .signature = "(J[I)Lcom/itsaky/androidide/treesitter/TSQueryMatch;",
    .fnPtr = nullptr
};

// Index of method setContainingByteRange of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setContainingByteRange__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setContainingByteRange
 * Signature: (JII)Z
 */
static JNINativeMethod TSQueryCursor_Native_setContainingByteRange= {
    .name = "setContainingByteRange",
    .signature = "(JII)Z",
    .fnPtr = nullptr
};

// Index of method setContainingPointRange of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setContainingPointRange__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setContainingPointRange
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z
 */
static JNINativeMethod TSQueryCursor_Native_setContainingPointRange= {
    .name = "setContainingPointRange",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSPoint;Lcom/itsaky/androidide/treesitter/TSPoint;)Z",
    .fnPtr = nullptr
};

// Index of method setMaxStartDepth of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_setMaxStartDepth__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    setMaxStartDepth
 * Signature: (JI)V
 */
static JNINativeMethod TSQueryCursor_Native_setMaxStartDepth= {
    .name = "setMaxStartDepth",
    .signature = "(JI)V",
    .fnPtr = nullptr
};

// Index of method removeMatch of class com.itsaky.androidide.treesitter.TSQueryCursor.Native in _TSQueryCursor_Native_METHODS array
#define TSQueryCursor_Native_removeMatch__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSQueryCursor.Native
 * Method:    removeMatch
 * Signature: (JI)V
 */
static JNINativeMethod TSQueryCursor_Native_removeMatch= {
    .name = "removeMatch",
    .signature = "(JI)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSQueryCursor$Native
void TSQueryCursor_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSQueryCursor_Native_METHODS
#define _TSQueryCursor_Native_METHOD_COUNT 16
// All native methods in class com/itsaky/androidide/treesitter/TSQueryCursor$Native
#define TSQueryCursor_Native_DefMethodsArray \
    JNINativeMethod _TSQueryCursor_Native_METHODS[] = { \
        TSQueryCursor_Native_newCursor, \
        TSQueryCursor_Native_delete, \
        TSQueryCursor_Native_exec, \
        TSQueryCursor_Native_execWithOptions, \
        TSQueryCursor_Native_releaseProgressCallback, \
        TSQueryCursor_Native_exceededMatchLimit, \
        TSQueryCursor_Native_setMatchLimit, \
        TSQueryCursor_Native_getMatchLimit, \
        TSQueryCursor_Native_setByteRange, \
        TSQueryCursor_Native_setPointRange, \
        TSQueryCursor_Native_nextMatch, \
        TSQueryCursor_Native_nextCapture, \
        TSQueryCursor_Native_setContainingByteRange, \
        TSQueryCursor_Native_setContainingPointRange, \
        TSQueryCursor_Native_setMaxStartDepth, \
        TSQueryCursor_Native_removeMatch, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSQueryCursor$Native with the given JNIEnv
#define TSQueryCursor_Native_AutoRegisterNatives(_env) \
    int _TSQueryCursor_Native_rc; \
    TSQueryCursor_Native__SetJniMethods(&_TSQueryCursor_Native_METHODS[0], _TSQueryCursor_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSQueryCursor_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSQueryCursor_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSQueryCursor_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSQueryCursor$Native"); \
    if (_TSQueryCursor_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSQueryCursor$Native"); \
        return JNI_ERR; \
    } \
    _TSQueryCursor_Native_rc = _env->RegisterNatives(_TSQueryCursor_Native_class, _TSQueryCursor_Native_METHODS, _TSQueryCursor_Native_METHOD_COUNT); \
    if (_TSQueryCursor_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSQueryCursor$Native'. Result: %d", _TSQueryCursor_Native_rc); \
        return _TSQueryCursor_Native_rc; \
    }\


#endif
#endif
