/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSQuery.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSQuery__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSQuery__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    newQuery
 * Signature: (Lcom/itsaky/androidide/treesitter/TSQuery;JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_newQuery
  (JNIEnv *env, jclass clazz, jobject, jlong, jstring);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_captureCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_patternCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    stringCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_stringCount
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    startByteForPattern
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_startByteForPattern
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    predicatesForPattern
 * Signature: (JI)[Lcom/itsaky/androidide/treesitter/TSQueryPredicateStep;
 */
JNIEXPORT jobjectArray JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_predicatesForPattern
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternRooted
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_patternRooted
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternNonLocal
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_patternNonLocal
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternGuaranteedAtStep
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_patternGuaranteedAtStep
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureNameForId
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_captureNameForId
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    stringValueForId
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_stringValueForId
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureQuantifierForId
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_captureQuantifierForId
  (JNIEnv *env, jclass clazz, jlong, jint, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_copy
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    endByteForPattern
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_endByteForPattern
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    disablePattern
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_disablePattern
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    disableCapture
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQuery_00024Native_disableCapture
  (JNIEnv *env, jclass clazz, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSQuery__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSQuery__Native_METHOD_SIGNATURES

// Index of method newQuery of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_newQuery__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    newQuery
 * Signature: (Lcom/itsaky/androidide/treesitter/TSQuery;JLjava/lang/String;)J
 */
static JNINativeMethod TSQuery_Native_newQuery= {
    .name = "newQuery",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSQuery;JLjava/lang/String;)J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSQuery_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method captureCount of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_captureCount__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureCount
 * Signature: (J)I
 */
static JNINativeMethod TSQuery_Native_captureCount= {
    .name = "captureCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method patternCount of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_patternCount__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternCount
 * Signature: (J)I
 */
static JNINativeMethod TSQuery_Native_patternCount= {
    .name = "patternCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method stringCount of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_stringCount__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    stringCount
 * Signature: (J)I
 */
static JNINativeMethod TSQuery_Native_stringCount= {
    .name = "stringCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method startByteForPattern of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_startByteForPattern__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    startByteForPattern
 * Signature: (JI)I
 */
static JNINativeMethod TSQuery_Native_startByteForPattern= {
    .name = "startByteForPattern",
    .signature = "(JI)I",
    .fnPtr = nullptr
};

// Index of method predicatesForPattern of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_predicatesForPattern__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    predicatesForPattern
 * Signature: (JI)[Lcom/itsaky/androidide/treesitter/TSQueryPredicateStep;
 */
static JNINativeMethod TSQuery_Native_predicatesForPattern= {
    .name = "predicatesForPattern",
    .signature = "(JI)[Lcom/itsaky/androidide/treesitter/TSQueryPredicateStep;",
    .fnPtr = nullptr
};

// Index of method patternRooted of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_patternRooted__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternRooted
 * Signature: (JI)Z
 */
static JNINativeMethod TSQuery_Native_patternRooted= {
    .name = "patternRooted",
    .signature = "(JI)Z",
    .fnPtr = nullptr
};

// Index of method patternNonLocal of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_patternNonLocal__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternNonLocal
 * Signature: (JI)Z
 */
static JNINativeMethod TSQuery_Native_patternNonLocal= {
    .name = "patternNonLocal",
    .signature = "(JI)Z",
    .fnPtr = nullptr
};

// Index of method patternGuaranteedAtStep of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_patternGuaranteedAtStep__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    patternGuaranteedAtStep
 * Signature: (JI)Z
 */
static JNINativeMethod TSQuery_Native_patternGuaranteedAtStep= {
    .name = "patternGuaranteedAtStep",
    .signature = "(JI)Z",
    .fnPtr = nullptr
};

// Index of method captureNameForId of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_captureNameForId__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureNameForId
 * Signature: (JI)Ljava/lang/String;
 */
static JNINativeMethod TSQuery_Native_captureNameForId= {
    .name = "captureNameForId",
    .signature = "(JI)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method stringValueForId of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_stringValueForId__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    stringValueForId
 * Signature: (JI)Ljava/lang/String;
 */
static JNINativeMethod TSQuery_Native_stringValueForId= {
    .name = "stringValueForId",
    .signature = "(JI)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method captureQuantifierForId of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_captureQuantifierForId__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    captureQuantifierForId
 * Signature: (JII)I
 */
static JNINativeMethod TSQuery_Native_captureQuantifierForId= {
    .name = "captureQuantifierForId",
    .signature = "(JII)I",
    .fnPtr = nullptr
};

// Index of method copy of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_copy__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    copy
 * Signature: (J)J
 */
static JNINativeMethod TSQuery_Native_copy= {
    .name = "copy",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method endByteForPattern of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_endByteForPattern__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    endByteForPattern
 * Signature: (JI)I
 */
static JNINativeMethod TSQuery_Native_endByteForPattern= {
    .name = "endByteForPattern",
    .signature = "(JI)I",
    .fnPtr = nullptr
};

// Index of method disablePattern of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_disablePattern__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    disablePattern
 * Signature: (JI)V
 */
static JNINativeMethod TSQuery_Native_disablePattern= {
    .name = "disablePattern",
    .signature = "(JI)V",
    .fnPtr = nullptr
};

// Index of method disableCapture of class com.itsaky.androidide.treesitter.TSQuery.Native in _TSQuery_Native_METHODS array
#define TSQuery_Native_disableCapture__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.TSQuery.Native
 * Method:    disableCapture
 * Signature: (J[BI)V
 */
static JNINativeMethod TSQuery_Native_disableCapture= {
    .name = "disableCapture",
    .signature = "(J[BI)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSQuery$Native
void TSQuery_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSQuery_Native_METHODS
#define _TSQuery_Native_METHOD_COUNT 17
// All native methods in class com/itsaky/androidide/treesitter/TSQuery$Native
#define TSQuery_Native_DefMethodsArray \
    JNINativeMethod _TSQuery_Native_METHODS[] = { \
        TSQuery_Native_newQuery, \
        TSQuery_Native_delete, \
        TSQuery_Native_captureCount, \
        TSQuery_Native_patternCount, \
        TSQuery_Native_stringCount, \
        TSQuery_Native_startByteForPattern, \
        TSQuery_Native_predicatesForPattern, \
        TSQuery_Native_patternRooted, \
        TSQuery_Native_patternNonLocal, \
        TSQuery_Native_patternGuaranteedAtStep, \
        TSQuery_Native_captureNameForId, \
        TSQuery_Native_stringValueForId, \
        TSQuery_Native_captureQuantifierForId, \
        TSQuery_Native_copy, \
        TSQuery_Native_endByteForPattern, \
        TSQuery_Native_disablePattern, \
        TSQuery_Native_disableCapture, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSQuery$Native with the given JNIEnv
#define TSQuery_Native_AutoRegisterNatives(_env) \
    int _TSQuery_Native_rc; \
    TSQuery_Native__SetJniMethods(&_TSQuery_Native_METHODS[0], _TSQuery_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSQuery_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSQuery_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSQuery_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSQuery$Native"); \
    if (_TSQuery_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSQuery$Native"); \
        return JNI_ERR; \
    } \
    _TSQuery_Native_rc = _env->RegisterNatives(_TSQuery_Native_class, _TSQuery_Native_METHODS, _TSQuery_Native_METHOD_COUNT); \
    if (_TSQuery_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSQuery$Native'. Result: %d", _TSQuery_Native_rc); \
        return _TSQuery_Native_rc; \
    }\


#endif
#endif
