/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSTree.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSTree__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSTree__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    edit
 * Signature: (JLcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_edit
  (JNIEnv *env, jclass clazz, jlong, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_copy
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    rootNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_rootNode
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    rootNodeWithOffset
 * Signature: (JILcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_rootNodeWithOffset
  (JNIEnv *env, jclass clazz, jlong, jint, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    changedRanges
 * Signature: (JJ)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
JNIEXPORT jobjectArray JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_changedRanges
  (JNIEnv *env, jclass clazz, jlong, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    includedRanges
 * Signature: (J)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
JNIEXPORT jobjectArray JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_includedRanges
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    getLanguage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_getLanguage
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    printDotGraph
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_printDotGraph
  (JNIEnv *env, jclass clazz, jlong, jint);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSTree__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSTree__Native_METHOD_SIGNATURES

// Index of method edit of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_edit__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    edit
 * Signature: (JLcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
static JNINativeMethod TSTree_Native_edit= {
    .name = "edit",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSInputEdit;)V",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSTree_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method copy of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_copy__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    copy
 * Signature: (J)J
 */
static JNINativeMethod TSTree_Native_copy= {
    .name = "copy",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method rootNode of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_rootNode__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    rootNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSTree_Native_rootNode= {
    .name = "rootNode",
    .signature = "(J)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method rootNodeWithOffset of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_rootNodeWithOffset__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    rootNodeWithOffset
 * Signature: (JILcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSTree_Native_rootNodeWithOffset= {
    .name = "rootNodeWithOffset",
    .signature = "(JILcom/itsaky/androidide/treesitter/TSPoint;)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method changedRanges of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_changedRanges__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    changedRanges
 * Signature: (JJ)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
static JNINativeMethod TSTree_Native_changedRanges= {
    .name = "changedRanges",
    .signature = "(JJ)[Lcom/itsaky/androidide/treesitter/TSRange;",
    .fnPtr = nullptr
};

// Index of method includedRanges of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_includedRanges__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    includedRanges
 * Signature: (J)[Lcom/itsaky/androidide/treesitter/TSRange;
 */
static JNINativeMethod TSTree_Native_includedRanges= {
    .name = "includedRanges",
    .signature = "(J)[Lcom/itsaky/androidide/treesitter/TSRange;",
    .fnPtr = nullptr
};

// Index of method getLanguage of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_getLanguage__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    getLanguage
 * Signature: (J)J
 */
static JNINativeMethod TSTree_Native_getLanguage= {
    .name = "getLanguage",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method printDotGraph of class com.itsaky.androidide.treesitter.TSTree.Native in _TSTree_Native_METHODS array
#define TSTree_Native_printDotGraph__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSTree.Native
 * Method:    printDotGraph
 * Signature: (JI)V
 */
static JNINativeMethod TSTree_Native_printDotGraph= {
    .name = "printDotGraph",
    .signature = "(JI)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSTree$Native
void TSTree_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSTree_Native_METHODS
#define _TSTree_Native_METHOD_COUNT 9
// All native methods in class com/itsaky/androidide/treesitter/TSTree$Native
#define TSTree_Native_DefMethodsArray \
    JNINativeMethod _TSTree_Native_METHODS[] = { \
        TSTree_Native_edit, \
        TSTree_Native_delete, \
        TSTree_Native_copy, \
        TSTree_Native_rootNode, \
        TSTree_Native_rootNodeWithOffset, \
        TSTree_Native_changedRanges, \
        TSTree_Native_includedRanges, \
        TSTree_Native_getLanguage, \
        TSTree_Native_printDotGraph, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSTree$Native with the given JNIEnv
#define TSTree_Native_AutoRegisterNatives(_env) \
    int _TSTree_Native_rc; \
    TSTree_Native__SetJniMethods(&_TSTree_Native_METHODS[0], _TSTree_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSTree_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSTree_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSTree_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSTree$Native"); \
    if (_TSTree_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSTree$Native"); \
        return JNI_ERR; \
    } \
    _TSTree_Native_rc = _env->RegisterNatives(_TSTree_Native_class, _TSTree_Native_METHODS, _TSTree_Native_METHOD_COUNT); \
    if (_TSTree_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSTree$Native'. Result: %d", _TSTree_Native_rc); \
        return _TSTree_Native_rc; \
    }\


#endif
#endif
