/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSTreeCursor.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSTreeCursor__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSTreeCursor__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_copy
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentDescendantIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentDescendantIndex
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentFieldId
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentFieldId
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentFieldName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentFieldName
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentNode
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentTreeCursorNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSTreeCursorNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentTreeCursorNode
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    depth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_depth
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoDescendant
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoDescendant
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChild
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoFirstChild
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChildForByte
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoFirstChildForByte
  (JNIEnv *env, jclass clazz, jlong, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChildForPoint
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoFirstChildForPoint
  (JNIEnv *env, jclass clazz, jlong, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoLastChild
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoLastChild
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoNextSibling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoNextSibling
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoParent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoParent
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoPreviousSibling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoPreviousSibling
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    newCursor
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_newCursor
  (JNIEnv *env, jclass clazz, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    reset
 * Signature: (JLcom/itsaky/androidide/treesitter/TSNode;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_reset
  (JNIEnv *env, jclass clazz, jlong, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    resetTo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_resetTo
  (JNIEnv *env, jclass clazz, jlong, jlong);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSTreeCursor__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSTreeCursor__Native_METHOD_SIGNATURES

// Index of method copy of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_copy__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    copy
 * Signature: (J)J
 */
static JNINativeMethod TSTreeCursor_Native_copy= {
    .name = "copy",
    .signature = "(J)J",
    .fnPtr = nullptr
};

// Index of method currentDescendantIndex of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_currentDescendantIndex__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentDescendantIndex
 * Signature: (J)I
 */
static JNINativeMethod TSTreeCursor_Native_currentDescendantIndex= {
    .name = "currentDescendantIndex",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method currentFieldId of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_currentFieldId__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentFieldId
 * Signature: (J)S
 */
static JNINativeMethod TSTreeCursor_Native_currentFieldId= {
    .name = "currentFieldId",
    .signature = "(J)S",
    .fnPtr = nullptr
};

// Index of method currentFieldName of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_currentFieldName__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentFieldName
 * Signature: (J)Ljava/lang/String;
 */
static JNINativeMethod TSTreeCursor_Native_currentFieldName= {
    .name = "currentFieldName",
    .signature = "(J)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method currentNode of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_currentNode__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
static JNINativeMethod TSTreeCursor_Native_currentNode= {
    .name = "currentNode",
    .signature = "(J)Lcom/itsaky/androidide/treesitter/TSNode;",
    .fnPtr = nullptr
};

// Index of method currentTreeCursorNode of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_currentTreeCursorNode__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    currentTreeCursorNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSTreeCursorNode;
 */
static JNINativeMethod TSTreeCursor_Native_currentTreeCursorNode= {
    .name = "currentTreeCursorNode",
    .signature = "(J)Lcom/itsaky/androidide/treesitter/TSTreeCursorNode;",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_delete__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSTreeCursor_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method depth of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_depth__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    depth
 * Signature: (J)I
 */
static JNINativeMethod TSTreeCursor_Native_depth= {
    .name = "depth",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method gotoDescendant of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoDescendant__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoDescendant
 * Signature: (JI)V
 */
static JNINativeMethod TSTreeCursor_Native_gotoDescendant= {
    .name = "gotoDescendant",
    .signature = "(JI)V",
    .fnPtr = nullptr
};

// Index of method gotoFirstChild of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoFirstChild__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChild
 * Signature: (J)Z
 */
static JNINativeMethod TSTreeCursor_Native_gotoFirstChild= {
    .name = "gotoFirstChild",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method gotoFirstChildForByte of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoFirstChildForByte__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChildForByte
 * Signature: (JI)J
 */
static JNINativeMethod TSTreeCursor_Native_gotoFirstChildForByte= {
    .name = "gotoFirstChildForByte",
    .signature = "(JI)J",
    .fnPtr = nullptr
};

// Index of method gotoFirstChildForPoint of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoFirstChildForPoint__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoFirstChildForPoint
 * Signature: (JLcom/itsaky/androidide/treesitter/TSPoint;)J
 */
static JNINativeMethod TSTreeCursor_Native_gotoFirstChildForPoint= {
    .name = "gotoFirstChildForPoint",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSPoint;)J",
    .fnPtr = nullptr
};

// Index of method gotoLastChild of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoLastChild__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoLastChild
 * Signature: (J)Z
 */
static JNINativeMethod TSTreeCursor_Native_gotoLastChild= {
    .name = "gotoLastChild",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method gotoNextSibling of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoNextSibling__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoNextSibling
 * Signature: (J)Z
 */
static JNINativeMethod TSTreeCursor_Native_gotoNextSibling= {
    .name = "gotoNextSibling",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method gotoParent of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoParent__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoParent
 * Signature: (J)Z
 */
static JNINativeMethod TSTreeCursor_Native_gotoParent= {
    .name = "gotoParent",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method gotoPreviousSibling of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_gotoPreviousSibling__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    gotoPreviousSibling
 * Signature: (J)Z
 */
static JNINativeMethod TSTreeCursor_Native_gotoPreviousSibling= {
    .name = "gotoPreviousSibling",
    .signature = "(J)Z",
    .fnPtr = nullptr
};

// Index of method newCursor of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_newCursor__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    newCursor
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)J
 */
static JNINativeMethod TSTreeCursor_Native_newCursor= {
    .name = "newCursor",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSNode;)J",
    .fnPtr = nullptr
};

// Index of method reset of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_reset__ARR_IDX 17

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    reset
 * Signature: (JLcom/itsaky/androidide/treesitter/TSNode;)V
 */
static JNINativeMethod TSTreeCursor_Native_reset= {
    .name = "reset",
    .signature = "(JLcom/itsaky/androidide/treesitter/TSNode;)V",
    .fnPtr = nullptr
};

// Index of method resetTo of class com.itsaky.androidide.treesitter.TSTreeCursor.Native in _TSTreeCursor_Native_METHODS array
#define TSTreeCursor_Native_resetTo__ARR_IDX 18

/*
 * Class:     com.itsaky.androidide.treesitter.TSTreeCursor.Native
 * Method:    resetTo
 * Signature: (JJ)V
 */
static JNINativeMethod TSTreeCursor_Native_resetTo= {
    .name = "resetTo",
    .signature = "(JJ)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSTreeCursor$Native
void TSTreeCursor_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSTreeCursor_Native_METHODS
#define _TSTreeCursor_Native_METHOD_COUNT 19
// All native methods in class com/itsaky/androidide/treesitter/TSTreeCursor$Native
#define TSTreeCursor_Native_DefMethodsArray \
    JNINativeMethod _TSTreeCursor_Native_METHODS[] = { \
        TSTreeCursor_Native_copy, \
        TSTreeCursor_Native_currentDescendantIndex, \
        TSTreeCursor_Native_currentFieldId, \
        TSTreeCursor_Native_currentFieldName, \
        TSTreeCursor_Native_currentNode, \
        TSTreeCursor_Native_currentTreeCursorNode, \
        TSTreeCursor_Native_delete, \
        TSTreeCursor_Native_depth, \
        TSTreeCursor_Native_gotoDescendant, \
        TSTreeCursor_Native_gotoFirstChild, \
        TSTreeCursor_Native_gotoFirstChildForByte, \
        TSTreeCursor_Native_gotoFirstChildForPoint, \
        TSTreeCursor_Native_gotoLastChild, \
        TSTreeCursor_Native_gotoNextSibling, \
        TSTreeCursor_Native_gotoParent, \
        TSTreeCursor_Native_gotoPreviousSibling, \
        TSTreeCursor_Native_newCursor, \
        TSTreeCursor_Native_reset, \
        TSTreeCursor_Native_resetTo, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSTreeCursor$Native with the given JNIEnv
#define TSTreeCursor_Native_AutoRegisterNatives(_env) \
    int _TSTreeCursor_Native_rc; \
    TSTreeCursor_Native__SetJniMethods(&_TSTreeCursor_Native_METHODS[0], _TSTreeCursor_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSTreeCursor_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSTreeCursor_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSTreeCursor_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSTreeCursor$Native"); \
    if (_TSTreeCursor_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSTreeCursor$Native"); \
        return JNI_ERR; \
    } \
    _TSTreeCursor_Native_rc = _env->RegisterNatives(_TSTreeCursor_Native_class, _TSTreeCursor_Native_METHODS, _TSTreeCursor_Native_METHOD_COUNT); \
    if (_TSTreeCursor_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSTreeCursor$Native'. Result: %d", _TSTreeCursor_Native_rc); \
        return _TSTreeCursor_Native_rc; \
    }\


#endif
#endif
