/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSUtils.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSUtils__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSUtils__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSUtils.Native
 * Method:    pointEdit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSPoint;ILcom/itsaky/androidide/treesitter/TSInputEdit;)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSUtils_00024Native_pointEdit
  (JNIEnv *env, jclass clazz, jobject, jint, jobject);

/*
 * Class:     com.itsaky.androidide.treesitter.TSUtils.Native
 * Method:    rangeEdit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSRange;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSUtils_00024Native_rangeEdit
  (JNIEnv *env, jclass clazz, jobject, jobject);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSUtils__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSUtils__Native_METHOD_SIGNATURES

// Index of method pointEdit of class com.itsaky.androidide.treesitter.TSUtils.Native in _TSUtils_Native_METHODS array
#define TSUtils_Native_pointEdit__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSUtils.Native
 * Method:    pointEdit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSPoint;ILcom/itsaky/androidide/treesitter/TSInputEdit;)I
 */
static JNINativeMethod TSUtils_Native_pointEdit= {
    .name = "pointEdit",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSPoint;ILcom/itsaky/androidide/treesitter/TSInputEdit;)I",
    .fnPtr = nullptr
};

// Index of method rangeEdit of class com.itsaky.androidide.treesitter.TSUtils.Native in _TSUtils_Native_METHODS array
#define TSUtils_Native_rangeEdit__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSUtils.Native
 * Method:    rangeEdit
 * Signature: (Lcom/itsaky/androidide/treesitter/TSRange;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
static JNINativeMethod TSUtils_Native_rangeEdit= {
    .name = "rangeEdit",
    .signature = "(Lcom/itsaky/androidide/treesitter/TSRange;Lcom/itsaky/androidide/treesitter/TSInputEdit;)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSUtils$Native
void TSUtils_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSUtils_Native_METHODS
#define _TSUtils_Native_METHOD_COUNT 2
// All native methods in class com/itsaky/androidide/treesitter/TSUtils$Native
#define TSUtils_Native_DefMethodsArray \
    JNINativeMethod _TSUtils_Native_METHODS[] = { \
        TSUtils_Native_pointEdit, \
        TSUtils_Native_rangeEdit, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSUtils$Native with the given JNIEnv
#define TSUtils_Native_AutoRegisterNatives(_env) \
    int _TSUtils_Native_rc; \
    TSUtils_Native__SetJniMethods(&_TSUtils_Native_METHODS[0], _TSUtils_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSUtils_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSUtils_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSUtils_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSUtils$Native"); \
    if (_TSUtils_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSUtils$Native"); \
        return JNI_ERR; \
    } \
    _TSUtils_Native_rc = _env->RegisterNatives(_TSUtils_Native_class, _TSUtils_Native_METHODS, _TSUtils_Native_METHOD_COUNT); \
    if (_TSUtils_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSUtils$Native'. Result: %d", _TSUtils_Native_rc); \
        return _TSUtils_Native_rc; \
    }\


#endif
#endif
