/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 UTF16StringFactory.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_string_UTF16StringFactory__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_string_UTF16StringFactory__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native
 * Method:    newString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16StringFactory_00024Native_newString
  (JNIEnv *env, jclass clazz, jstring source);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native
 * Method:    newStringBytes
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16StringFactory_00024Native_newStringBytes
  (JNIEnv *env, jclass clazz, jbyteArray bytes, jint off, jint len);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_string_UTF16StringFactory__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_string_UTF16StringFactory__Native_METHOD_SIGNATURES

// Index of method newString of class com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native in _UTF16StringFactory_Native_METHODS array
#define UTF16StringFactory_Native_newString__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native
 * Method:    newString
 * Signature: (Ljava/lang/String;)J
 */
static JNINativeMethod UTF16StringFactory_Native_newString= {
    .name = "newString",
    .signature = "(Ljava/lang/String;)J",
    .fnPtr = nullptr
};

// Index of method newStringBytes of class com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native in _UTF16StringFactory_Native_METHODS array
#define UTF16StringFactory_Native_newStringBytes__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16StringFactory.Native
 * Method:    newStringBytes
 * Signature: ([BII)J
 */
static JNINativeMethod UTF16StringFactory_Native_newStringBytes= {
    .name = "newStringBytes",
    .signature = "([BII)J",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native
void UTF16StringFactory_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _UTF16StringFactory_Native_METHODS
#define _UTF16StringFactory_Native_METHOD_COUNT 2
// All native methods in class com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native
#define UTF16StringFactory_Native_DefMethodsArray \
    JNINativeMethod _UTF16StringFactory_Native_METHODS[] = { \
        UTF16StringFactory_Native_newString, \
        UTF16StringFactory_Native_newStringBytes, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native with the given JNIEnv
#define UTF16StringFactory_Native_AutoRegisterNatives(_env) \
    int _UTF16StringFactory_Native_rc; \
    UTF16StringFactory_Native__SetJniMethods(&_UTF16StringFactory_Native_METHODS[0], _UTF16StringFactory_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _UTF16StringFactory_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_UTF16StringFactory_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _UTF16StringFactory_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native"); \
    if (_UTF16StringFactory_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native"); \
        return JNI_ERR; \
    } \
    _UTF16StringFactory_Native_rc = _env->RegisterNatives(_UTF16StringFactory_Native_class, _UTF16StringFactory_Native_METHODS, _UTF16StringFactory_Native_METHOD_COUNT); \
    if (_UTF16StringFactory_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/string/UTF16StringFactory$Native'. Result: %d", _UTF16StringFactory_Native_rc); \
        return _UTF16StringFactory_Native_rc; \
    }\


#endif
#endif
