/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 UTF16String.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_string_UTF16String__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_string_UTF16String__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    byteAt
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_byteAt
  (JNIEnv *env, jclass clazz, jlong pointer, jint index);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    setByteAt
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_setByteAt
  (JNIEnv *env, jclass clazz, jlong pointer, jint index, jbyte b);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    chatAt
 * Signature: (JI)C
 */
JNIEXPORT jchar JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_chatAt
  (JNIEnv *env, jclass clazz, jlong pointer, jint index);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    setCharAt
 * Signature: (JIC)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_setCharAt
  (JNIEnv *env, jclass clazz, jlong pointer, jint index, jchar c);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    append
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_append
  (JNIEnv *env, jclass clazz, jlong pointer, jstring str);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    appendPart
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_appendPart
  (JNIEnv *env, jclass clazz, jlong pointer, jstring str, jint fromIndex, jint len);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    insert
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_insert
  (JNIEnv *env, jclass clazz, jlong pointer, jstring str, jint index);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    deleteChars
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_deleteChars
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    deleteBytes
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_deleteBytes
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    replaceChars
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_replaceChars
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end, jstring str);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    replaceBytes
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_replaceBytes
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end, jstring str);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    substring_chars
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_substring_1chars
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    substring_bytes
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_substring_1bytes
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    subjstring_chars
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_subjstring_1chars
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    subjstring_bytes
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_subjstring_1bytes
  (JNIEnv *env, jclass clazz, jlong pointer, jint start, jint end);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_toString
  (JNIEnv *env, jclass clazz, jlong pointer);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_length
  (JNIEnv *env, jclass clazz, jlong pointer);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    byteLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_byteLength
  (JNIEnv *env, jclass clazz, jlong pointer);

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    erase
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_string_UTF16String_00024Native_erase
  (JNIEnv *env, jclass clazz, jlong pointer);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_string_UTF16String__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_string_UTF16String__Native_METHOD_SIGNATURES

// Index of method byteAt of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_byteAt__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    byteAt
 * Signature: (JI)B
 */
static JNINativeMethod UTF16String_Native_byteAt= {
    .name = "byteAt",
    .signature = "(JI)B",
    .fnPtr = nullptr
};

// Index of method setByteAt of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_setByteAt__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    setByteAt
 * Signature: (JIB)V
 */
static JNINativeMethod UTF16String_Native_setByteAt= {
    .name = "setByteAt",
    .signature = "(JIB)V",
    .fnPtr = nullptr
};

// Index of method chatAt of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_chatAt__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    chatAt
 * Signature: (JI)C
 */
static JNINativeMethod UTF16String_Native_chatAt= {
    .name = "chatAt",
    .signature = "(JI)C",
    .fnPtr = nullptr
};

// Index of method setCharAt of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_setCharAt__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    setCharAt
 * Signature: (JIC)V
 */
static JNINativeMethod UTF16String_Native_setCharAt= {
    .name = "setCharAt",
    .signature = "(JIC)V",
    .fnPtr = nullptr
};

// Index of method append of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_append__ARR_IDX 4

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    append
 * Signature: (JLjava/lang/String;)V
 */
static JNINativeMethod UTF16String_Native_append= {
    .name = "append",
    .signature = "(JLjava/lang/String;)V",
    .fnPtr = nullptr
};

// Index of method appendPart of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_appendPart__ARR_IDX 5

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    appendPart
 * Signature: (JLjava/lang/String;II)V
 */
static JNINativeMethod UTF16String_Native_appendPart= {
    .name = "appendPart",
    .signature = "(JLjava/lang/String;II)V",
    .fnPtr = nullptr
};

// Index of method insert of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_insert__ARR_IDX 6

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    insert
 * Signature: (JLjava/lang/String;I)V
 */
static JNINativeMethod UTF16String_Native_insert= {
    .name = "insert",
    .signature = "(JLjava/lang/String;I)V",
    .fnPtr = nullptr
};

// Index of method deleteChars of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_deleteChars__ARR_IDX 7

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    deleteChars
 * Signature: (JII)V
 */
static JNINativeMethod UTF16String_Native_deleteChars= {
    .name = "deleteChars",
    .signature = "(JII)V",
    .fnPtr = nullptr
};

// Index of method deleteBytes of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_deleteBytes__ARR_IDX 8

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    deleteBytes
 * Signature: (JII)V
 */
static JNINativeMethod UTF16String_Native_deleteBytes= {
    .name = "deleteBytes",
    .signature = "(JII)V",
    .fnPtr = nullptr
};

// Index of method replaceChars of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_replaceChars__ARR_IDX 9

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    replaceChars
 * Signature: (JIILjava/lang/String;)V
 */
static JNINativeMethod UTF16String_Native_replaceChars= {
    .name = "replaceChars",
    .signature = "(JIILjava/lang/String;)V",
    .fnPtr = nullptr
};

// Index of method replaceBytes of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_replaceBytes__ARR_IDX 10

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    replaceBytes
 * Signature: (JIILjava/lang/String;)V
 */
static JNINativeMethod UTF16String_Native_replaceBytes= {
    .name = "replaceBytes",
    .signature = "(JIILjava/lang/String;)V",
    .fnPtr = nullptr
};

// Index of method substring_chars of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_substring_chars__ARR_IDX 11

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    substring_chars
 * Signature: (JII)J
 */
static JNINativeMethod UTF16String_Native_substring_chars= {
    .name = "substring_chars",
    .signature = "(JII)J",
    .fnPtr = nullptr
};

// Index of method substring_bytes of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_substring_bytes__ARR_IDX 12

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    substring_bytes
 * Signature: (JII)J
 */
static JNINativeMethod UTF16String_Native_substring_bytes= {
    .name = "substring_bytes",
    .signature = "(JII)J",
    .fnPtr = nullptr
};

// Index of method subjstring_chars of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_subjstring_chars__ARR_IDX 13

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    subjstring_chars
 * Signature: (JII)Ljava/lang/String;
 */
static JNINativeMethod UTF16String_Native_subjstring_chars= {
    .name = "subjstring_chars",
    .signature = "(JII)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method subjstring_bytes of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_subjstring_bytes__ARR_IDX 14

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    subjstring_bytes
 * Signature: (JII)Ljava/lang/String;
 */
static JNINativeMethod UTF16String_Native_subjstring_bytes= {
    .name = "subjstring_bytes",
    .signature = "(JII)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method toString of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_toString__ARR_IDX 15

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
static JNINativeMethod UTF16String_Native_toString= {
    .name = "toString",
    .signature = "(J)Ljava/lang/String;",
    .fnPtr = nullptr
};

// Index of method length of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_length__ARR_IDX 16

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    length
 * Signature: (J)I
 */
static JNINativeMethod UTF16String_Native_length= {
    .name = "length",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method byteLength of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_byteLength__ARR_IDX 17

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    byteLength
 * Signature: (J)I
 */
static JNINativeMethod UTF16String_Native_byteLength= {
    .name = "byteLength",
    .signature = "(J)I",
    .fnPtr = nullptr
};

// Index of method erase of class com.itsaky.androidide.treesitter.string.UTF16String.Native in _UTF16String_Native_METHODS array
#define UTF16String_Native_erase__ARR_IDX 18

/*
 * Class:     com.itsaky.androidide.treesitter.string.UTF16String.Native
 * Method:    erase
 * Signature: (J)V
 */
static JNINativeMethod UTF16String_Native_erase= {
    .name = "erase",
    .signature = "(J)V",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/string/UTF16String$Native
void UTF16String_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _UTF16String_Native_METHODS
#define _UTF16String_Native_METHOD_COUNT 19
// All native methods in class com/itsaky/androidide/treesitter/string/UTF16String$Native
#define UTF16String_Native_DefMethodsArray \
    JNINativeMethod _UTF16String_Native_METHODS[] = { \
        UTF16String_Native_byteAt, \
        UTF16String_Native_setByteAt, \
        UTF16String_Native_chatAt, \
        UTF16String_Native_setCharAt, \
        UTF16String_Native_append, \
        UTF16String_Native_appendPart, \
        UTF16String_Native_insert, \
        UTF16String_Native_deleteChars, \
        UTF16String_Native_deleteBytes, \
        UTF16String_Native_replaceChars, \
        UTF16String_Native_replaceBytes, \
        UTF16String_Native_substring_chars, \
        UTF16String_Native_substring_bytes, \
        UTF16String_Native_subjstring_chars, \
        UTF16String_Native_subjstring_bytes, \
        UTF16String_Native_toString, \
        UTF16String_Native_length, \
        UTF16String_Native_byteLength, \
        UTF16String_Native_erase, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/string/UTF16String$Native with the given JNIEnv
#define UTF16String_Native_AutoRegisterNatives(_env) \
    int _UTF16String_Native_rc; \
    UTF16String_Native__SetJniMethods(&_UTF16String_Native_METHODS[0], _UTF16String_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _UTF16String_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_UTF16String_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _UTF16String_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/string/UTF16String$Native"); \
    if (_UTF16String_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/string/UTF16String$Native"); \
        return JNI_ERR; \
    } \
    _UTF16String_Native_rc = _env->RegisterNatives(_UTF16String_Native_class, _UTF16String_Native_METHODS, _UTF16String_Native_METHOD_COUNT); \
    if (_UTF16String_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/string/UTF16String$Native'. Result: %d", _UTF16String_Native_rc); \
        return _UTF16String_Native_rc; \
    }\


#endif
#endif
