/* DO NOT EDIT THIS FILE - it is machine generated (Manually recreated for migration) */
/**
 * @author android_zero
 * 定义了 Java 层 TSWasmStore.Native 类中 native 方法的元数据和注册逻辑。
 */

#include <jni.h>
#include "ts__log.h"

#ifndef __TS_LOG_DEBUG
#ifdef NDEBUG
#define __TS_LOG_DEBUG 0
#else
#define __TS_LOG_DEBUG 1
#endif
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSWasmStore__Native_METHODS
#define _Included_com_itsaky_androidide_treesitter_TSWasmStore__Native_METHODS

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    newStore
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSWasmStore_00024Native_newStore
  (JNIEnv *env, jclass clazz);

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSWasmStore_00024Native_delete
  (JNIEnv *env, jclass clazz, jlong);

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    loadLanguage
 * Signature: (JLjava/lang/String;[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSWasmStore_00024Native_loadLanguage
  (JNIEnv *env, jclass clazz, jlong, jstring, jbyteArray, jint);

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    languageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSWasmStore_00024Native_languageCount
  (JNIEnv *env, jclass clazz, jlong);

#ifdef __cplusplus
}
#endif

#ifndef _Included_com_itsaky_androidide_treesitter_TSWasmStore__Native_METHOD_SIGNATURES
#define _Included_com_itsaky_androidide_treesitter_TSWasmStore__Native_METHOD_SIGNATURES

// Index of method newStore of class com.itsaky.androidide.treesitter.TSWasmStore.Native in _TSWasmStore_Native_METHODS array
#define TSWasmStore_Native_newStore__ARR_IDX 0

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    newStore
 * Signature: ()J
 */
static JNINativeMethod TSWasmStore_Native_newStore= {
    .name = "newStore",
    .signature = "()J",
    .fnPtr = nullptr
};

// Index of method delete of class com.itsaky.androidide.treesitter.TSWasmStore.Native in _TSWasmStore_Native_METHODS array
#define TSWasmStore_Native_delete__ARR_IDX 1

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    delete
 * Signature: (J)V
 */
static JNINativeMethod TSWasmStore_Native_delete= {
    .name = "delete",
    .signature = "(J)V",
    .fnPtr = nullptr
};

// Index of method loadLanguage of class com.itsaky.androidide.treesitter.TSWasmStore.Native in _TSWasmStore_Native_METHODS array
#define TSWasmStore_Native_loadLanguage__ARR_IDX 2

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    loadLanguage
 * Signature: (JLjava/lang/String;[BI)J
 */
static JNINativeMethod TSWasmStore_Native_loadLanguage= {
    .name = "loadLanguage",
    .signature = "(JLjava/lang/String;[BI)J",
    .fnPtr = nullptr
};

// Index of method languageCount of class com.itsaky.androidide.treesitter.TSWasmStore.Native in _TSWasmStore_Native_METHODS array
#define TSWasmStore_Native_languageCount__ARR_IDX 3

/*
 * Class:     com.itsaky.androidide.treesitter.TSWasmStore.Native
 * Method:    languageCount
 * Signature: (J)I
 */
static JNINativeMethod TSWasmStore_Native_languageCount= {
    .name = "languageCount",
    .signature = "(J)I",
    .fnPtr = nullptr
};


// This function is called in order to set the actual
// implementations of the native methods defined in class
// com/itsaky/androidide/treesitter/TSWasmStore$Native
void TSWasmStore_Native__SetJniMethods(JNINativeMethod *methods, int count);

// Number of elements in _TSWasmStore_Native_METHODS
#define _TSWasmStore_Native_METHOD_COUNT 4
// All native methods in class com/itsaky/androidide/treesitter/TSWasmStore$Native
#define TSWasmStore_Native_DefMethodsArray \
    JNINativeMethod _TSWasmStore_Native_METHODS[] = { \
        TSWasmStore_Native_newStore, \
        TSWasmStore_Native_delete, \
        TSWasmStore_Native_loadLanguage, \
        TSWasmStore_Native_languageCount, \
    };

#ifndef SET_JNI_METHOD
#define SET_JNI_METHOD(_mths, _mth, _func) { \
    void *ptr = (void *)(&_func); \
    (_mths + _mth##__ARR_IDX)->fnPtr = ptr; \
    if (__TS_LOG_DEBUG == 1) { \
        LOGD(LOG_TAG, "SET_JNI_METHOD: %s to %p", _mth.name, ptr); \
        LOGD(LOG_TAG, "SET_JNI_METHOD: fnPtr = %p", _mths[_mth##__ARR_IDX].fnPtr); \
    } \
}
#endif


// Registers the native methods of class com/itsaky/androidide/treesitter/TSWasmStore$Native with the given JNIEnv
#define TSWasmStore_Native_AutoRegisterNatives(_env) \
    int _TSWasmStore_Native_rc; \
    TSWasmStore_Native__SetJniMethods(&_TSWasmStore_Native_METHODS[0], _TSWasmStore_Native_METHOD_COUNT); \
    if (__TS_LOG_DEBUG == 1) { \
    for (int i = 0; i < _TSWasmStore_Native_METHOD_COUNT; ++i) { \
        JNINativeMethod mth = *(_TSWasmStore_Native_METHODS + i); \
        LOGD(LOG_TAG, "Register native method: '%s', '%s', '%p'", mth.name, mth.signature, mth.fnPtr); } \
    } \
    jclass _TSWasmStore_Native_class = _env->FindClass("com/itsaky/androidide/treesitter/TSWasmStore$Native"); \
    if (_TSWasmStore_Native_class == NULL) { \
        LOGE(LOG_TAG, "Failed to find class com/itsaky/androidide/treesitter/TSWasmStore$Native"); \
        return JNI_ERR; \
    } \
    _TSWasmStore_Native_rc = _env->RegisterNatives(_TSWasmStore_Native_class, _TSWasmStore_Native_METHODS, _TSWasmStore_Native_METHOD_COUNT); \
    if (_TSWasmStore_Native_rc != JNI_OK) { \
        LOGE(LOG_TAG, "Failed to register native methods for class 'com/itsaky/androidide/treesitter/TSWasmStore$Native'. Result: %d", _TSWasmStore_Native_rc); \
        return _TSWasmStore_Native_rc; \
    }\


#endif
#endif
