/*
 *  This file is part of AndroidIDE.
 *
 *  AndroidIDE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  AndroidIDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *   along with AndroidIDE.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.itsaky.androidide.repository.materials

import java.io.DataInputStream
import java.io.File
import java.util.zip.ZipFile

/**
 * Minimal Java `.class` file reader. Produces a textual representation of the class
 * suitable for inspection inside the editor.
 *
 * The reader only relies on the standard library and intentionally does not pull in any
 * ASM/CFR/Jadx/FernFlower dependency. It supports the common class file features
 * (constant pool, access flags, this/super, interfaces, fields, methods, attributes)
 * and is able to disassemble the code attribute of each method into smali-like assembly.
 *
 * Two rendering modes are provided:
 *  * [renderJava] – Java source-like output: package, class declaration with super-class
 *    and interfaces, and method signatures.
 *  * [renderSmali] – Smali-style output: `.class`/`.super`/`.implements` directives,
 *    field and method declarations with annotations, and a per-method bytecode listing.
 *
 * @author android_zero
 */
internal object ClassFileAnalyzer {

  private const val MAGIC = 0xCAFEBABE.toInt()

  fun read(bytes: ByteArray): ClassModel? = runCatching {
    DataInputStream(bytes.inputStream()).use { it.parse() }
  }.getOrNull()

  fun readZipEntry(archive: File, entryName: String): ClassModel? = runCatching {
    ZipFile(archive).use { zip ->
      val entry = zip.getEntry(entryName) ?: return@runCatching null
      zip.getInputStream(entry).use { stream -> DataInputStream(stream).use { it.parse() } }
    }
  }.getOrNull()

  fun renderJava(model: ClassModel, engine: String): String = buildString {
    appendLine("// Decompiled by $engine")
    appendLine(
        "// Source: ${model.thisClass} (class file version " +
            "%.1f)".format(model.majorVersion / 10.0),
    )
    appendLine("// Generated by ZeroStudio built-in class reader")
    appendLine()
    if (model.packageName.isNotEmpty()) {
      appendLine("package ${model.packageName};")
      appendLine()
    }
    val access = javaAccessFlags(model.accessFlags, isField = false, isInterface = false)
    val kind =
        when {
          (model.accessFlags and ACC_ANNOTATION) != 0 -> "@interface"
          (model.accessFlags and ACC_INTERFACE) != 0 -> "interface"
          (model.accessFlags and ACC_ENUM) != 0 -> "enum"
          else -> "class"
        }
    val extends =
        when {
          (model.accessFlags and ACC_INTERFACE) != 0 -> ""
          model.superClass.isNullOrEmpty() || model.superClass == "java/lang/Object" -> ""
          else -> " extends ${model.superClass!!.replace('/', '.')}"
        }
    val implements =
        if (model.interfaces.isEmpty()) ""
        else
            (if ((model.accessFlags and ACC_INTERFACE) != 0) " extends " else " implements ") +
                model.interfaces.joinToString(", ") { it.replace('/', '.') }
    append("$access $kind ${model.simpleName}$extends$implements {\n")
    for (field in model.fields) {
      append("    ")
      append(javaAccessFlags(field.accessFlags, isField = true, isInterface = false))
      append(' ')
      append(descriptorToJava(field.descriptor))
      append(' ')
      append(field.name)
      if (field.constantValue != null) append(" = ${field.constantValue}")
      append(";\n")
    }
    if (model.fields.isNotEmpty() && model.methods.isNotEmpty()) append('\n')
    for (method in model.methods) {
      val methodAccess =
          javaAccessFlags(method.accessFlags, isField = false, isInterface = (model.accessFlags and ACC_INTERFACE) != 0)
      val methodName = if (method.name == "<init>") model.simpleName else method.name
      val params = parseMethodDescriptor(method.descriptor)
      val returnType = descriptorToJava(params.first())
      val paramList =
          params.drop(1).joinToString(", ") { descriptorToJava(it) }
      val throws =
          if (method.exceptions.isEmpty()) ""
          else " throws " + method.exceptions.joinToString(", ") { it.replace('/', '.') }
      append("    $methodAccess $returnType $methodName($paramList)$throws")
      if (method.isAbstract || (model.accessFlags and ACC_INTERFACE) != 0) {
        append(";\n")
      } else {
        append(" {\n")
        if (method.codeSize > 0) {
          append("        // bytecode size = ${method.codeSize} bytes\n")
        }
        append("    }\n")
      }
    }
    append("}\n")
  }

  fun renderSmali(model: ClassModel): String = buildString {
    appendLine("# Disassembled by ZeroStudio smali reader")
    appendLine(
        "# Source: ${model.thisClass} (class file version " +
            "%.1f)".format(model.majorVersion / 10.0),
    )
    val access = smaliAccessFlags(model.accessFlags, isField = false, isInterface = false)
    append(".class $access ${model.thisClass}\n")
    if (!model.superClass.isNullOrEmpty() && model.superClass != "java/lang/Object") {
      append(".super ${model.superClass}\n")
    }
    for (iface in model.interfaces) {
      append(".implements $iface\n")
    }
    if (model.fields.isNotEmpty()) {
      appendLine()
      appendLine("# fields")
      for (field in model.fields) {
        val fAccess = smaliAccessFlags(field.accessFlags, isField = true, isInterface = false)
        append(".field $fAccess ${field.name}:${field.descriptor}\n")
      }
    }
    if (model.methods.isNotEmpty()) {
      appendLine()
      appendLine("# methods")
      for (method in model.methods) {
        val mAccess =
            smaliAccessFlags(
                method.accessFlags,
                isField = false,
                isInterface = (model.accessFlags and ACC_INTERFACE) != 0,
            )
        append(".method $mAccess ${method.name}${method.descriptor}\n")
        if (method.codeSize > 0) {
          appendLine(
              "    # code: ${method.codeSize} bytes, ${method.maxStack} stack, ${method.maxLocals} locals"
          )
          for (line in method.disassembly) {
            append("    $line\n")
          }
        }
        append(".end method\n\n")
      }
    }
  }

  // region Parsing

  private fun DataInputStream.parse(): ClassModel {
    val magic = readInt()
    if (magic != MAGIC) error("Not a Java class file (bad magic 0x${"%08x".format(magic)})")
    val minor = readUnsignedShort()
    val major = readUnsignedShort()
    val cpCount = readUnsignedShort()
    val cp = ConstantPool(capacity = cpCount)
    var i = 1
    while (i < cpCount) {
      val tag = readUnsignedByte()
      when (tag) {
        CpTag.UTF8 -> cp.entries[i] = CpUtf8(readUtf())
        CpTag.INTEGER -> cp.entries[i] = CpInteger(readInt())
        CpTag.FLOAT -> cp.entries[i] = CpFloat(readFloat())
        CpTag.LONG -> {
          cp.entries[i] = CpLong(readLong())
          i++
          cp.entries[i] = CpPlaceholder
        }
        CpTag.DOUBLE -> {
          cp.entries[i] = CpDouble(readDouble())
          i++
          cp.entries[i] = CpPlaceholder
        }
        CpTag.CLASS -> cp.entries[i] = CpClass(readUnsignedShort())
        CpTag.STRING -> cp.entries[i] = CpString(readUnsignedShort())
        CpTag.FIELDREF -> {
          cp.entries[i] = CpRef(CpRefKind.FIELD, readUnsignedShort(), readUnsignedShort())
        }
        CpTag.METHODREF -> {
          cp.entries[i] = CpRef(CpRefKind.METHOD, readUnsignedShort(), readUnsignedShort())
        }
        CpTag.INTERFACEMETHODREF -> {
          cp.entries[i] = CpRef(CpRefKind.INTERFACE, readUnsignedShort(), readUnsignedShort())
        }
        CpTag.NAMEANDTYPE -> cp.entries[i] = CpNameAndType(readUnsignedShort(), readUnsignedShort())
        CpTag.METHODHANDLE -> {
          readUnsignedByte()
          readUnsignedShort()
          cp.entries[i] = CpPlaceholder
        }
        CpTag.METHODTYPE -> {
          cp.entries[i] = CpPlaceholder
          readUnsignedShort()
        }
        CpTag.INVOKEDYNAMIC -> {
          cp.entries[i] = CpPlaceholder
          readUnsignedShort()
          readUnsignedShort()
        }
        CpTag.MODULE -> {
          cp.entries[i] = CpPlaceholder
          readUnsignedShort()
        }
        CpTag.PACKAGE -> {
          cp.entries[i] = CpPlaceholder
          readUnsignedShort()
        }
        else -> error("Unknown constant pool tag: $tag at $i")
      }
      i++
    }
    val accessFlags = readUnsignedShort()
    val thisClassIdx = readUnsignedShort()
    val superClassIdx = readUnsignedShort()
    val thisName = (cp[thisClassIdx] as? CpClass)?.let { cp.utf(it.nameIndex) } ?: "<unknown>"
    val superName = (cp[superClassIdx] as? CpClass)?.let { cp.utf(it.nameIndex) }
    val ifacesCount = readUnsignedShort()
    val interfaces = Array(ifacesCount) {
      (cp[readUnsignedShort()] as? CpClass)?.let { cp.utf(it.nameIndex) } ?: "<unknown>"
    }
    val fieldsCount = readUnsignedShort()
    val fields = Array(fieldsCount) { parseField(cp) }
    val methodsCount = readUnsignedShort()
    val methods = Array(methodsCount) { parseMethod(cp) }
    val attributesCount = readUnsignedShort()
    repeat(attributesCount) {
      readUnsignedShort()
      val length = readInt()
      skipBytes(length)
    }
    val (pkg, simple) = splitName(thisName)
    return ClassModel(
        thisClass = thisName,
        packageName = pkg,
        simpleName = simple,
        superClass = superName,
        interfaces = interfaces.toList(),
        accessFlags = accessFlags,
        majorVersion = major,
        minorVersion = minor,
        constantPool = cp,
        fields = fields.toList(),
        methods = methods.toList(),
    )
  }

  private fun DataInputStream.parseField(cp: ConstantPool): FieldModel {
    val accessFlags = readUnsignedShort()
    val nameIdx = readUnsignedShort()
    val descIdx = readUnsignedShort()
    val attributesCount = readUnsignedShort()
    var constantValue: String? = null
    repeat(attributesCount) {
      val tag = readUnsignedShort()
      val length = readInt()
      if (cp.utf(tag) == "ConstantValue") {
        val idx = readUnsignedShort()
        constantValue = formatConstant(cp[idx], cp)
        skipBytes(length - 2)
      } else {
        skipBytes(length)
      }
    }
    return FieldModel(
        name = cp.utf(nameIdx),
        descriptor = cp.utf(descIdx),
        accessFlags = accessFlags,
        constantValue = constantValue,
    )
  }

  private fun DataInputStream.parseMethod(cp: ConstantPool): MethodModel {
    val accessFlags = readUnsignedShort()
    val nameIdx = readUnsignedShort()
    val descIdx = readUnsignedShort()
    val attributesCount = readUnsignedShort()
    var maxStack = 0
    var maxLocals = 0
    var codeSize = 0
    var disassembly: List<String> = emptyList()
    val exceptions = mutableListOf<String>()
    repeat(attributesCount) {
      val tag = readUnsignedShort()
      val length = readInt()
      val tagName = cp.utf(tag)
      if (tagName == "Code") {
        maxStack = readUnsignedShort()
        maxLocals = readUnsignedShort()
        codeSize = readInt()
        val code = readN(codeSize)
        disassembly = BytecodeDisassembler.disassemble(code, cp)
        val exCount = readUnsignedShort()
        repeat(exCount) {
          readUnsignedShort()
          readUnsignedShort()
          readUnsignedShort()
          readUnsignedShort()
        }
        val subAttrs = readUnsignedShort()
        repeat(subAttrs) {
          val sTag = readUnsignedShort()
          val sLen = readInt()
          skipBytes(sLen)
          if (sTag == 0xFFFF) skipBytes(0)
        }
      } else if (tagName == "Exceptions") {
        val count = readUnsignedShort()
        repeat(count) {
          val idx = readUnsignedShort()
          val name = (cp[idx] as? CpClass)?.let { cp.utf(it.nameIndex) }
          if (name != null) exceptions += name
        }
      } else {
        skipBytes(length)
      }
    }
    return MethodModel(
        name = cp.utf(nameIdx),
        descriptor = cp.utf(descIdx),
        accessFlags = accessFlags,
        codeSize = codeSize,
        maxStack = maxStack,
        maxLocals = maxLocals,
        disassembly = disassembly,
        exceptions = exceptions,
    )
  }

  private fun DataInputStream.readN(count: Int): ByteArray {
    val out = ByteArray(count)
    var read = 0
    while (read < count) {
      val r = this.read(out, read, count - read)
      if (r <= 0) break
      read += r
    }
    if (read < count) error("Unexpected end of stream while reading $count bytes (got $read)")
    return out
  }

  // endregion

  // region Helpers

  private fun splitName(internal: String): Pair<String, String> {
    val lastSlash = internal.lastIndexOf('/')
    return if (lastSlash < 0) "" to internal
    else internal.substring(0, lastSlash) to internal.substring(lastSlash + 1)
  }

  private fun formatConstant(entry: ClassFileAnalyzerCpEntry?, cp: ConstantPool): String? = when (entry) {
    is CpString -> "\"${cp.utf(entry.stringIndex)}\""
    is CpInteger -> entry.value.toString()
    is CpLong -> entry.value.toString() + "L"
    is CpFloat -> "${entry.value}f"
    is CpDouble -> "${entry.value}d"
    else -> null
  }

  internal fun descriptorToJava(descriptor: String): String {
    if (descriptor.startsWith("(")) return descriptor
    return when {
      descriptor.startsWith("L") && descriptor.endsWith(";") ->
          descriptor.substring(1, descriptor.length - 1).replace('/', '.')
      descriptor.startsWith("[") -> descriptorToJava(descriptor.substring(1)) + "[]"
      descriptor == "V" -> "void"
      descriptor == "Z" -> "boolean"
      descriptor == "B" -> "byte"
      descriptor == "C" -> "char"
      descriptor == "S" -> "short"
      descriptor == "I" -> "int"
      descriptor == "J" -> "long"
      descriptor == "F" -> "float"
      descriptor == "D" -> "double"
      else -> descriptor
    }
  }

  internal fun parseMethodDescriptor(descriptor: String): List<String> {
    if (!descriptor.startsWith("(")) return listOf(descriptor)
    val out = mutableListOf<String>()
    var i = 1
    while (i < descriptor.length && descriptor[i] != ')') {
      val start = i
      while (i < descriptor.length) {
        val c = descriptor[i]
        if (c == 'L' && (i == start || descriptor[i - 1] == '[')) {
          i++
          while (i < descriptor.length && descriptor[i] != ';') i++
          if (i < descriptor.length) i++
          break
        } else if (c == '[') {
          i++
        } else {
          i++
          break
        }
      }
      out += descriptor.substring(start, i)
    }
    if (i < descriptor.length && descriptor[i] == ')') {
      out += descriptor.substring(i + 1)
    } else {
      out += "V"
    }
    return out
  }

  private fun javaAccessFlags(flags: Int, isField: Boolean, isInterface: Boolean): String {
    val parts = mutableListOf<String>()
    if ((flags and ACC_PUBLIC) != 0) parts += "public"
    if ((flags and ACC_PRIVATE) != 0) parts += "private"
    if ((flags and ACC_PROTECTED) != 0) parts += "protected"
    if ((flags and ACC_STATIC) != 0) parts += "static"
    if ((flags and ACC_FINAL) != 0) parts += "final"
    if (!isInterface) {
      if ((flags and ACC_ABSTRACT) != 0) parts += "abstract"
    }
    if (!isField) {
      if ((flags and ACC_SYNCHRONIZED) != 0) parts += "synchronized"
      if ((flags and ACC_NATIVE) != 0) parts += "native"
    } else {
      if ((flags and ACC_VOLATILE) != 0) parts += "volatile"
      if ((flags and ACC_TRANSIENT) != 0) parts += "transient"
    }
    return if (parts.isEmpty()) "" else parts.joinToString(" ")
  }

  private fun smaliAccessFlags(flags: Int, isField: Boolean, isInterface: Boolean): String {
    val parts = mutableListOf<String>()
    if ((flags and ACC_PUBLIC) != 0) parts += "public"
    if ((flags and ACC_PRIVATE) != 0) parts += "private"
    if ((flags and ACC_PROTECTED) != 0) parts += "protected"
    if ((flags and ACC_STATIC) != 0) parts += "static"
    if ((flags and ACC_FINAL) != 0) parts += "final"
    if (!isField) {
      if ((flags and ACC_SYNCHRONIZED) != 0) parts += "synchronized"
      if ((flags and ACC_BRIDGE) != 0) parts += "bridge"
      if ((flags and ACC_VARARGS) != 0) parts += "varargs"
      if ((flags and ACC_NATIVE) != 0) parts += "native"
      if ((flags and ACC_ABSTRACT) != 0) parts += "abstract"
    } else {
      if ((flags and ACC_VOLATILE) != 0) parts += "volatile"
      if ((flags and ACC_TRANSIENT) != 0) parts += "transient"
    }
    if ((flags and ACC_SYNTHETIC) != 0) parts += "synthetic"
    if ((flags and ACC_ENUM) != 0) parts += "enum"
    return if (parts.isEmpty()) "" else parts.joinToString(" ")
  }

  // endregion

  // region Access flag constants

  private const val ACC_PUBLIC = 0x0001
  private const val ACC_PRIVATE = 0x0002
  private const val ACC_PROTECTED = 0x0004
  private const val ACC_STATIC = 0x0008
  private const val ACC_FINAL = 0x0010
  private const val ACC_SYNCHRONIZED = 0x0020
  private const val ACC_BRIDGE = 0x0040
  private const val ACC_VARARGS = 0x0080
  private const val ACC_NATIVE = 0x0100
  private const val ACC_INTERFACE = 0x0200
  private const val ACC_ABSTRACT = 0x0400
  private const val ACC_STRICT = 0x0800
  private const val ACC_SYNTHETIC = 0x1000
  private const val ACC_ANNOTATION = 0x2000
  private const val ACC_ENUM = 0x4000
  // Field-only access flag bits share the same numeric values as ACC_BRIDGE/ACC_VARARGS.
  private const val ACC_VOLATILE = 0x0040
  private const val ACC_TRANSIENT = 0x0080

  // endregion

  // region Models

  data class ClassModel(
      val thisClass: String,
      val packageName: String,
      val simpleName: String,
      val superClass: String?,
      val interfaces: List<String>,
      val accessFlags: Int,
      val majorVersion: Int,
      val minorVersion: Int,
      val constantPool: ConstantPool,
      val fields: List<FieldModel>,
      val methods: List<MethodModel>,
  )

  data class FieldModel(
      val name: String,
      val descriptor: String,
      val accessFlags: Int,
      val constantValue: String?,
  )

  data class MethodModel(
      val name: String,
      val descriptor: String,
      val accessFlags: Int,
      val codeSize: Int,
      val maxStack: Int,
      val maxLocals: Int,
      val disassembly: List<String>,
      val exceptions: List<String>,
  ) {
    val isAbstract: Boolean
      get() = (accessFlags and ACC_ABSTRACT) != 0
  }

  // endregion
}

internal class ConstantPool(capacity: Int) {
  val entries: Array<ClassFileAnalyzerCpEntry?> = arrayOfNulls(capacity)

  operator fun get(index: Int): ClassFileAnalyzerCpEntry? {
    if (index <= 0 || index >= entries.size) return null
    return entries[index]
  }

  fun utf(index: Int): String {
    val entry = this[index] as? CpUtf8 ?: return "<invalid#$index>"
    return entry.value
  }
}

internal sealed interface ClassFileAnalyzerCpEntry
internal data object CpPlaceholder : ClassFileAnalyzerCpEntry
internal data class CpUtf8(val value: String) : ClassFileAnalyzerCpEntry
internal data class CpInteger(val value: Int) : ClassFileAnalyzerCpEntry
internal data class CpFloat(val value: Float) : ClassFileAnalyzerCpEntry
internal data class CpLong(val value: Long) : ClassFileAnalyzerCpEntry
internal data class CpDouble(val value: Double) : ClassFileAnalyzerCpEntry
internal data class CpClass(val nameIndex: Int) : ClassFileAnalyzerCpEntry
internal data class CpString(val stringIndex: Int) : ClassFileAnalyzerCpEntry
internal data class CpRef(val kind: CpRefKind, val classIndex: Int, val nameAndTypeIndex: Int) :
    ClassFileAnalyzerCpEntry
internal data class CpNameAndType(val nameIndex: Int, val descriptorIndex: Int) :
    ClassFileAnalyzerCpEntry

internal enum class CpRefKind { FIELD, METHOD, INTERFACE }

private object CpTag {
  const val UTF8 = 1
  const val INTEGER = 3
  const val FLOAT = 4
  const val LONG = 5
  const val DOUBLE = 6
  const val CLASS = 7
  const val STRING = 8
  const val FIELDREF = 9
  const val METHODREF = 10
  const val INTERFACEMETHODREF = 11
  const val NAMEANDTYPE = 12
  const val METHODHANDLE = 15
  const val METHODTYPE = 16
  const val INVOKEDYNAMIC = 18
  const val MODULE = 19
  const val PACKAGE = 20
}
