name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Choose the compilation type (assembleDebug or assembleRelease)'
        required: true
        default: 'assembleRelease'
        type: choice
        options:
          - assemble
          - assembleDebug
          - assembleRelease

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install basic system dependency packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip protobuf-compiler python3 python3-pip wget curl

      - name: Configure JDK 21 (Zulu 21.0.9)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Configuring a Gradle 8.13 environment
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Install the specified NDK and Android SDK CMake (3.22.1)
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.1.12297006" "cmake;3.22.1"

      - name: Install higher CMake version (3.31.1) via pip
        run: |
          sudo pip3 install cmake==3.31.1 --break-system-packages
          CMAKE_DATA_DIR=$(python3 -c "import cmake, os; print(os.path.join(os.path.dirname(cmake.__file__), 'data'))")
          echo "cmake.dir=$CMAKE_DATA_DIR" >> local.properties
          
          cmake --version
          protoc --version
          python3 --version

      - name: Grant execution permissions to the Gradle wrapper
        run: chmod +x ./gradlew

      - name: Compile APK
        env:
          # 限制 Gradle JVM 最大使用 5GB 内存，不开启守护进程以免内存驻留
          GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx5g -XX:MaxMetaspaceSize=1g' -Dorg.gradle.daemon=false"
          # 限制 CMake 底层的 Ninja 并发数为 2，防止 C++ 编译器吃光内存

          # export CMAKE_BUILD_PARALLEL_LEVEL=2
          CMAKE_BUILD_PARALLEL_LEVEL: "2"
        run: |
          # 使用 --max-workers=2 限制模块并发
          gradle ${{ github.event.inputs.build_type }} --stacktrace --build-cache --max-workers=3

      - name: Upload app-arm64-v8a-release.apk
        if: github.event.inputs.build_type == 'assembleRelease' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release.apk
          path: core/app/build/outputs/apk/release/app-arm64-v8a-release.apk
          compression-level: 0

      - name: Upload app-armeabi-v7a-release.apk
        if: github.event.inputs.build_type == 'assembleRelease' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release.apk
          path: core/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
          compression-level: 0

      - name: Upload app-x86_64-release.apk
        if: github.event.inputs.build_type == 'assembleRelease' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-release.apk
          path: core/app/build/outputs/apk/release/app-x86_64-release.apk
          compression-level: 0

      - name: Upload app-arm64-v8a-debug.apk
        if: github.event.inputs.build_type == 'assembleDebug' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-debug.apk
          path: core/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
          compression-level: 0

      - name: Upload app-armeabi-v7a-debug.apk
        if: github.event.inputs.build_type == 'assembleDebug' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-debug.apk
          path: core/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
          compression-level: 0

      - name: Upload app-x86_64-debug.apk
        if: github.event.inputs.build_type == 'assembleDebug' || github.event.inputs.build_type == 'assemble'
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-debug.apk
          path: core/app/build/outputs/apk/debug/app-x86_64-debug.apk
          compression-level: 0